import type { ClientPortalProfile } from "../src/lib/clientPortalApi";
import type { PublicStore, StoreProduct } from "../src/lib/storeApi";

export const visualStore: PublicStore = {
  id: "visual-store-fixture",
  name: "Agência Visual de Testes",
  slug: "visual-fixture",
  tagline: "Viagens de teste, sem dados de produção",
  description: "Vitrine sintética usada exclusivamente pela suíte visual.",
  logoUrl: null,
  faviconUrl: null,
  bannerUrl: null,
  bannerMobileUrl: null,
  primaryColor: "#1E5B8C",
  secondaryColor: "#5D3E2A",
  accentColor: "#D8A646",
  contactEmail: "fixture@example.invalid",
  contactPhone: null,
  contactWhatsapp: null,
  contactAddress: null,
  socialInstagram: null,
  socialFacebook: null,
  socialYoutube: null,
  seoTitle: null,
  seoDescription: null,
  seoKeywords: null,
  paymentMethods: ["pix", "credit_card"],
  stripeEnabled: false,
  stripePublicKey: null,
  shippingPolicy: null,
  returnPolicy: null,
  cancellationPolicy: null,
  privacyPolicy: null,
  termsOfService: null,
  isActive: true,
  maintenanceMode: false,
  couponsEnabled: true,
  referralsEnabled: true,
  seatMapEnabled: false,
  minInstallments: 1,
  maxInstallments: 6,
  installmentFee: "0",
  minOrderValue: null,
  minDepositAmount: null,
  pixQrDeliveryMode: "screen",
};

export const visualProduct: StoreProduct = {
  id: "visual-product-fixture",
  storeId: visualStore.id,
  categoryId: "visual-category-fixture",
  tripId: "visual-trip-fixture",
  accommodationId: null,
  availableSeats: 18,
  totalCapacity: 24,
  departureDate: "2030-05-15T12:00:00.000Z",
  returnDate: "2030-05-18T12:00:00.000Z",
  inclusions: ["Transporte", "Acompanhamento de guia"],
  tripType: "excursion",
  originCity: "Crato",
  originState: "CE",
  destinationCity: "Nova Olinda",
  destinationState: "CE",
  departureTime: "07:00",
  returnTime: "18:00",
  showSeatMap: false,
  boardingPoints: [{ id: "visual-boarding-point", name: "Praça da Sé", time: "07:00" }],
  tripVideos: [],
  type: "trip",
  name: "Rota dos Geossítios do Araripe",
  slug: "rota-geossitios-araripe",
  shortDescription: "Uma viagem de teste pela Chapada do Araripe.",
  description: "Roteiro sintético para verificar a apresentação de detalhes, valores e ações.",
  price: "2650.00",
  comparePrice: "2950.00",
  costPrice: null,
  onSale: false,
  salePrice: null,
  saleStartsAt: null,
  saleEndsAt: null,
  trackInventory: true,
  stockQuantity: 18,
  allowBackorder: false,
  hasDates: true,
  startDate: "2030-05-15T12:00:00.000Z",
  endDate: "2030-05-18T12:00:00.000Z",
  images: [],
  thumbnail: null,
  gallery: [],
  features: ["Guia local", "Grupo reduzido"],
  includes: ["Transporte", "Guia"],
  excludes: ["Refeições não indicadas"],
  requirements: ["Documento oficial com foto"],
  destination: "Nova Olinda, CE",
  durationDays: 4,
  durationNights: 3,
  productCity: "Nova Olinda",
  productState: "CE",
  country: "Brasil",
  hasVariants: false,
  variants: [],
  metaTitle: null,
  metaDescription: null,
  metaKeywords: null,
  isFeatured: true,
  order: 1,
  ratingAverage: "4.9",
  ratingCount: 12,
  status: "active",
  publishedAt: "2030-01-01T12:00:00.000Z",
  viewsCount: 30,
  salesCount: 4,
  createdAt: "2030-01-01T12:00:00.000Z",
  updatedAt: "2030-01-01T12:00:00.000Z",
  partnerProductId: null,
  sellerName: null,
};

export const visualProfile: ClientPortalProfile = {
  user: {
    id: "visual-user-fixture",
    name: "Viajante de Teste",
    email: "viajante@example.invalid",
    cpf: null,
    referralCode: "VIAJANTE-TESTE",
    createdAt: "2025-01-01T12:00:00.000Z",
  },
  client: {
    id: "visual-client-fixture",
    name: "Viajante de Teste",
    email: "viajante@example.invalid",
    phone: "(88) 90000-0000",
    cpf: null,
    birthDate: "1990-01-01",
    addressCity: "Crato",
    addressState: "CE",
    referralCode: "VIAJANTE-TESTE",
    musicalPreferences: "Forró",
    favoriteDrink: "Suco de caju",
    dreamDestinations: ["Lençóis Maranhenses"],
    foodPreferences: "Comida regional",
    travelPreference: "Natureza",
    travelInterests: ["Trilhas", "Cultura"],
    likesPhotosVideos: true,
    preferredDestinationTypes: ["Praias", "Montanhas"],
    ambassadorOptIn: false,
    customerCode: "VC-TESTE-001",
  },
  tenant: {
    id: visualStore.id,
    name: visualStore.name,
    slug: visualStore.slug,
    logoUrl: null,
    primaryColor: visualStore.primaryColor,
    npsCategories: { transport: true, service: true, organization: true, guide: true },
  },
  reservations: [
    {
      id: "visual-reservation-fixture",
      reservationNumber: "VIS-TESTE-001",
      status: "confirmed",
      voucherCode: "VCH-TESTE-001",
      totalValue: 2650,
      paidValue: 650,
      balance: 2000,
      financialSummary: {
        totalAmount: 2650,
        amountPaid: 650,
        amountRemaining: 2000,
        reservationValid: true,
      },
      seatsCount: 2,
      paymentMethod: "pix",
      storeOrderId: "visual-order-fixture",
      createdAt: "2026-08-01T12:00:00.000Z",
      tripName: visualProduct.name,
      tripDestination: "Nova Olinda, CE",
      tripDepartureDate: visualProduct.departureDate ?? null,
      tripReturnDate: visualProduct.returnDate ?? null,
      tripType: "excursion",
      boardingPointName: "Praça da Sé",
      boardingPointTime: "07:00",
      npsSubmitted: false,
    },
  ],
  referral: {
    code: "VIAJANTE-TESTE",
    referralCodeStatus: "active",
    totalReferrals: 2,
    completedReferrals: 1,
    pendingReferrals: 1,
    totalEarnings: "125.00",
    creditBalance: "125.00",
    shareMessage: "Vamos viajar juntos!",
    currentTierLevel: "bronze",
    currentTierLabel: "Bronze",
    currentTierMultiplier: 1,
    tierProgress: 1,
    nextTierMin: 3,
    nextTierLabel: "Prata",
    nextTierRemaining: 2,
    nextTierMultiplier: 1.25,
    pointsPerReferral: 100,
    wallet: {
      availableCredit: 125,
      pendingCredit: 50,
      usedCredit: 0,
      expiringCredit: 0,
      expiringOn: null,
    },
  },
  stats: { totalSpent: 2650 },
  loyalty: {
    availablePoints: 1250,
    totalPoints: 1800,
    tier: "silver",
    programName: "Clube de Viagens",
    pointsPerReal: 1,
    realPerPoint: 0.01,
    minRedeemPoints: 100,
    tierBenefits: { bronze: ["Pontos por viagem"], silver: ["Pontos por viagem", "Ofertas exclusivas"] },
    recentTransactions: [],
  },
};

export const visualReferral = {
  id: "visual-referral-fixture",
  referredName: "Pessoa de Teste",
  referredEmail: "pessoa@example.invalid",
  status: "pending",
  convertedAt: null,
  bonusAmount: "50.00",
  bonusPaid: false,
  bonusPaidAt: null,
  bonusCreditUsedAt: null,
  bonusCreditOrderId: null,
  bonusCreditUsedAmount: null,
  createdAt: "2026-08-02T12:00:00.000Z",
  expiresAt: "2030-05-01T12:00:00.000Z",
  bonusReleasesAt: "2030-05-01T12:00:00.000Z",
  bonusBlocked: false,
  reversalReason: null,
  loyaltyPoints: null,
};

export const visualOrder = {
  id: "visual-order-fixture",
  orderNumber: "VIS-TESTE-001",
  status: "pending",
  customerName: "Viajante de Teste",
  customerEmail: "viajante@example.invalid",
  customerPhone: "(88) 90000-0000",
  subtotal: "2650.00",
  totalAmount: "2650.00",
  amountPaid: "650.00",
  amountRemaining: "2000.00",
  depositAmount: "650.00",
  paymentMethod: "pix",
  items: [
    {
      id: "visual-order-item-fixture",
      productId: visualProduct.id,
      productName: visualProduct.name,
      productSlug: visualProduct.slug,
      quantity: 1,
      unitPrice: "2650.00",
      totalPrice: "2650.00",
      productType: "trip",
      tripId: visualProduct.tripId,
      reservationId: "visual-reservation-fixture",
    },
  ],
  reservations: [],
  createdAt: "2026-08-01T12:00:00.000Z",
  reservationExpiresAt: "2030-05-14T12:00:00.000Z",
  paymentToken: "visual-payment-token",
};

export const visualCreatedOrder = {
  ...visualOrder,
  amountPaid: "0.00",
  amountRemaining: "2650.00",
  depositAmount: null,
  financialSummary: {
    source: "order" as const,
    subtotal: 2650,
    discountAmount: 0,
    totalAmount: 2650,
    depositRequested: 0,
    paidAmount: 0,
    amountRemaining: 2650,
    minimumRequired: 0,
    reservationValid: false,
    states: {
      order: "pending",
      reservation: "pending",
      payment: "pending" as const,
    },
    diagnostics: {
      hasLegacyDivergence: false,
      issues: [],
      legacy: null,
    },
  },
};

export const visualCategory = {
  id: "visual-category-fixture",
  storeId: visualStore.id,
  tenantId: visualStore.id,
  name: "Viagens de natureza",
  slug: "natureza",
  description: "Pacotes sintéticos para teste visual.",
  imageUrl: null,
  parentId: null,
  position: 1,
  isActive: true,
  createdAt: "2030-01-01T12:00:00.000Z",
  updatedAt: "2030-01-01T12:00:00.000Z",
};