export const supportTicketSsePayloadsWithUnsafeEventIds = [
  { eventId: "event-with-cr\rframe", type: "ticket", ticketId: "ticket-unsafe" },
  { eventId: "event-with-lf\nframe", type: "ticket", ticketId: "ticket-unsafe" },
  { eventId: "event-with-nul\u0000frame", type: "ticket", ticketId: "ticket-unsafe" },
  { eventId: "event-with-control\u001fbyte", type: "ticket", ticketId: "ticket-unsafe" },
  { eventId: "event-with-del\u007fbyte", type: "ticket", ticketId: "ticket-unsafe" },
  { eventId: "event-with-c1\u0085byte", type: "ticket", ticketId: "ticket-unsafe" },
  { eventId: "event-with-line-separator\u2028byte", type: "ticket", ticketId: "ticket-unsafe" },
  { eventId: "event-with-paragraph-separator\u2029byte", type: "ticket", ticketId: "ticket-unsafe" },
] as const;

export const malformedSupportTicketSsePayloads: unknown[] = [
  null,
  [],
  "not-an-object",
  { type: "ticket", ticketId: "ticket-missing-event-id" },
  { eventId: "", type: "ticket", ticketId: "ticket-empty-event-id" },
  { eventId: "   ", type: "ticket", ticketId: "ticket-whitespace-event-id" },
  { eventId: 42, type: "ticket", ticketId: "ticket-invalid-event-id" },
  { eventId: "ticket-missing-id", type: "ticket" },
  { eventId: "ticket-null-id", type: "ticket", ticketId: null },
  { eventId: "ticket-empty-id", type: "ticket", ticketId: "" },
  { eventId: "ticket-whitespace-id", type: "ticket", ticketId: "   " },
  { eventId: "queue-unexpected-id", type: "queues", ticketId: "ticket-123" },
  { eventId: "queue-missing-null", type: "queues" },
  { eventId: "refresh-unexpected-id", type: "refresh", ticketId: "ticket-123" },
  { eventId: "unknown-type", type: "reservation", ticketId: null },
  { eventId: "e".repeat(65), type: "ticket", ticketId: "ticket-valid" },
  { eventId: "event-valid", type: "ticket", ticketId: "t".repeat(65) },
  ...supportTicketSsePayloadsWithUnsafeEventIds,
];
