import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    testTimeout: 15_000,
    include: [
      "src/__tests__/client-dream-destinations.integration.test.ts",
      "src/__tests__/ghost-reservation.test.ts",
      "src/__tests__/expired-reservations.test.ts",
      "src/__tests__/loyalty-points-booking.test.ts",
      "src/__tests__/reservation-patch-deal-sync.test.ts",
      "src/__tests__/checkout-race-condition-db-integration.test.ts",
      "src/__tests__/client-email-link-lock-db-integration.test.ts",
      "src/__tests__/insights-sales-cycle-integration.test.ts",
      "src/__tests__/loyalty-clawback-integration.test.ts",
      "src/__tests__/admin-cancel-referral-integration.test.ts",
      "src/__tests__/abandoned-order-referrals-integration.test.ts",
      "src/__tests__/backup-export-integration.test.ts",
      "src/__tests__/backup-import.test.ts",
      "src/__tests__/subscription-upgrade-lock.integration.test.ts",
      "src/__tests__/paid-bonus-reversal-integration.test.ts",
      "src/__tests__/referral-payment-concurrency-integration.test.ts",
      "src/__tests__/persist-order-first-purchase-concurrency-integration.test.ts",
      "src/__tests__/reservation-referral-payment-reversal-integration.test.ts",
      "src/__tests__/payment-expiry-concurrency.integration.test.ts",
      "src/__tests__/unlink-client-from-trips-concurrency-integration.test.ts",
      "src/__tests__/referral-reversal-gaps.test.ts",
      "src/__tests__/referral-source-constraint.test.ts",
      "src/__tests__/reservation-patch-deal-sync.test.ts",
      "src/__tests__/room-assignments.integration.test.ts",
      "src/__tests__/accommodation-capacity.integration.test.ts",
    ],
  },
});
