import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Check, Copy, Download, Link2, MessageCircle, QrCode } from "lucide-react";

type ShareReferral = { code?: string | null; referrerName?: string | null; referrerWhatsapp?: string | null; bonusAmount?: string | number | null };
type ShareData = { link: string; qrCodeDataUrl: string };
interface Props {
  open: boolean; onOpenChange: (open: boolean) => void; data?: ShareData; loading: boolean;
  referral: ShareReferral | null; shareMessage?: string | null; copiedLink: boolean; copiedMessage: boolean;
  canCopyImage: boolean; onCopyLink: () => void; onCopyMessage: (message: string) => void;
  onCopyQr: (dataUrl: string, code: string) => void; onWhatsappQr: (dataUrl: string, code: string, phone: string, link: string) => void;
  whatsappUrl: string | null; isValidWhatsapp: (phone?: string | null) => boolean; onClose: () => void;
}
export function ReferralShareDialog({ open, onOpenChange, data, loading, referral, shareMessage, copiedLink, copiedMessage, canCopyImage, onCopyLink, onCopyMessage, onCopyQr, onWhatsappQr, whatsappUrl, isValidWhatsapp, onClose }: Props) {
  const message = shareMessage ? shareMessage.replace(/\{nome\}/g, referral?.referrerName ?? "").replace(/\{codigo\}/g, referral?.code ?? "").replace(/\{link\}/g, data?.link ?? "") : "";
  const preview = shareMessage && !/\{link\}/.test(shareMessage) ? `${message}\n${data?.link ?? ""}` : message;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-sm"><DialogHeader><DialogTitle className="flex items-center gap-2"><MessageCircle className="w-4 h-4 text-blue-600" />Compartilhar indicação</DialogTitle><DialogDescription>Envie o link ou QR-code ao indicador para facilitar o compartilhamento.</DialogDescription></DialogHeader>
    {loading ? <div className="flex items-center justify-center py-10 text-muted-foreground text-sm gap-2"><QrCode className="w-5 h-5 animate-pulse" />Gerando link e QR-code…</div> : data ? <div className="space-y-4"><div className="space-y-1.5"><p className="text-xs font-semibold text-muted-foreground uppercase flex items-center gap-1"><Link2 className="w-3.5 h-3.5" />Link de indicação</p><div className="flex items-center gap-2"><Input readOnly value={data.link} className="text-xs font-mono bg-muted/50 flex-1 min-w-0" /><Button size="sm" variant="outline" onClick={onCopyLink}>{copiedLink ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}</Button></div>{copiedLink && <p className="text-xs text-green-600"><Check className="inline w-3 h-3" /> Link copiado!</p>}</div>{shareMessage && <div className="space-y-1.5"><p className="text-xs font-semibold text-muted-foreground uppercase">Mensagem <Button size="sm" variant="outline" onClick={() => onCopyMessage(preview)} className="ml-auto h-6 px-2">{copiedMessage ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}</Button></p><div className="rounded-md border bg-muted/50 px-3 py-2 text-xs whitespace-pre-wrap">{preview}</div></div>}<div className="space-y-2"><p className="text-xs font-semibold text-muted-foreground uppercase flex items-center gap-1"><QrCode className="w-3.5 h-3.5" />QR-code</p><div className="flex justify-center"><img src={data.qrCodeDataUrl} alt="QR-code de indicação" className="w-48 h-48 border rounded-lg p-2 bg-white" /></div><p className="text-xs text-center text-muted-foreground">Escaneie para acessar o link de indicação</p><div className="flex justify-center items-center gap-3 flex-wrap"><a href={data.qrCodeDataUrl} download={`qrcode-${referral?.code ?? "referral"}.png`} className="inline-flex items-center gap-1.5 text-xs text-blue-600"><Download className="w-3.5 h-3.5" />Baixar QR-code</a><button type="button" onClick={() => onCopyQr(data.qrCodeDataUrl, referral?.code ?? "referral")} className="inline-flex items-center gap-1.5 text-xs text-blue-600">{canCopyImage ? <><Copy className="w-3.5 h-3.5" />Copiar imagem</> : <><Download className="w-3.5 h-3.5" />Baixar QR-code</>}</button>{isValidWhatsapp(referral?.referrerWhatsapp) && <button type="button" onClick={() => onWhatsappQr(data.qrCodeDataUrl, referral?.code ?? "referral", referral!.referrerWhatsapp!, data.link)} className="inline-flex items-center gap-1.5 text-xs text-green-700"><MessageCircle className="w-3.5 h-3.5" />Enviar QR-code pelo WhatsApp</button>}</div></div></div> : <div className="py-8 text-center text-muted-foreground text-sm">Erro ao gerar o link. Tente novamente.</div>}
    <DialogFooter className="flex-col sm:flex-row gap-2"><Button variant="outline" onClick={onClose}>Fechar</Button>{data && <><Button variant="outline" disabled={!whatsappUrl} asChild={!!whatsappUrl}><a href={whatsappUrl ?? "#"} target="_blank" rel="noopener noreferrer"><MessageCircle className="w-4 h-4 mr-2" />Enviar via WhatsApp</a></Button><Button onClick={onCopyLink} className="bg-blue-600 hover:bg-blue-700">{copiedLink ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}{copiedLink ? "Copiado!" : "Copiar link"}</Button></>}</DialogFooter>
  </DialogContent></Dialog>;
}