import { useMemo, useRef, useState, type ReactNode } from "react";
import {
  ArrowDown, ArrowLeft, ArrowRight, ArrowUpDown, BadgeCheck, Bell, BriefcaseBusiness, Copy,
  CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, CircleAlert, Clock3,
  Compass, CreditCard, Download, FileText, Filter, Heart, History, LayoutGrid, MapPin,
  MoreHorizontal, Plane, Plus, Search, Send, ShieldCheck, Sparkles, Star, Tag, Trash2,
  Upload, UserRound, Users, Wallet
} from "lucide-react";

type Client = {
  id: string; name: string; email: string; whatsapp: string; phone: string; city: string;
  state: string; origin: string; trip: string; classification: string; status: string;
  total: number; balance: number; purchase: number; churn: number; cpf: string;
  birthday: string; instagram: string; tags: string[]; observations: string; nps: number;
  tripDate: string; reservation: string; embarkation: string; seat: string; tripType: string;
  package: string; insurance: boolean; minor: boolean; ticketPrice: number;
  passengers: number; discount: number; paid: number; installments: number;
  commission: number; paymentMethod: string; seller: string; reason: string; rating: number;
  profession: string; favoriteDrink: string; music: string; food: string; dreams: string;
  interests: string[]; feedback: string; ambassador: boolean; createdAt?: string;
};

const seed: Client[] = [
  { id: "1", name: "Mariana Alves", email: "mariana.alves@email.com", whatsapp: "+55 31 99876-3210", phone: "(31) 3344-2211", city: "Belo Horizonte", state: "MG", origin: "Indicação", trip: "Lençóis Maranhenses", classification: "VIP", status: "Ativo", total: 18450, balance: 0, purchase: 92, churn: 8, cpf: "***.***.***-42", birthday: "14/08/1988", instagram: "@mariana.alves", tags: ["VIP", "Família", "Praia"], observations: "Prefere experiências exclusivas e hotéis boutique. Viaja com a filha nas férias escolares.", nps: 10, tripDate: "18 jul, 2025", reservation: "RES-2418", embarkation: "Belo Horizonte", seat: "14A · 14B", tripType: "Lazer", package: "Circuito Essencial · Casal", insurance: true, minor: true, ticketPrice: 18450, passengers: 2, discount: 550, paid: 18450, installments: 6, commission: 1291.5, paymentMethod: "Cartão de crédito", seller: "Ana Ribeiro", reason: "Férias em família", rating: 5, profession: "Arquiteta", favoriteDrink: "Vinho branco", music: "MPB", food: "Culinária regional", dreams: "Fernando de Noronha, Japão", interests: ["Praia", "Gastronomia", "Natureza"], feedback: "A equipe cuidou de cada detalhe. Foi a melhor viagem da nossa família.", ambassador: true },
  { id: "2", name: "Ricardo Mendes", email: "ricardo.mendes@gmail.com", whatsapp: "+55 11 98765-1098", phone: "", city: "São Paulo", state: "SP", origin: "Instagram", trip: "Patagônia Argentina", classification: "Cliente", status: "Ativo", total: 9250, balance: 1450, purchase: 76, churn: 24, cpf: "***.***.***-08", birthday: "02/11/1979", instagram: "@ricardomendes", tags: ["Aventura", "Montanha"], observations: "Viajante frequente, gosta de roteiros de aventura. Não gosta de excursões grandes.", nps: 9, tripDate: "09 set, 2025", reservation: "RES-2394", embarkation: "São Paulo", seat: "08C", tripType: "Aventura", package: "Patagônia sem pressa", insurance: true, minor: false, ticketPrice: 9250, passengers: 1, discount: 0, paid: 7800, installments: 4, commission: 647.5, paymentMethod: "Pix + cartão", seller: "Ana Ribeiro", reason: "Aventura", rating: 5, profession: "Fotógrafo", favoriteDrink: "Café", music: "Rock", food: "Vegetariana", dreams: "Atacama, Dolomitas", interests: ["Aventura", "Natureza", "Fotografia"], feedback: "Roteiro incrível. Quero voltar no verão.", ambassador: false },
  { id: "3", name: "Camila Ferreira", email: "camila.ferreira@outlook.com", whatsapp: "+55 21 99654-7788", phone: "", city: "Rio de Janeiro", state: "RJ", origin: "Site", trip: "", classification: "Prospecto", status: "Lead", total: 0, balance: 0, purchase: 58, churn: 42, cpf: "***.***.***-16", birthday: "27/03/1993", instagram: "@camilaf", tags: ["Lua de mel", "Cultura"], observations: "Planeja viagem de lua de mel para o primeiro semestre. Retornar com opções de Portugal.", nps: 8, tripDate: "", reservation: "", embarkation: "Rio de Janeiro", seat: "", tripType: "Lua de mel", package: "", insurance: false, minor: false, ticketPrice: 0, passengers: 2, discount: 0, paid: 0, installments: 1, commission: 0, paymentMethod: "A definir", seller: "Pedro Lima", reason: "Lua de mel", rating: 4, profession: "Médica", favoriteDrink: "Espumante", music: "Indie", food: "Mediterrânea", dreams: "Portugal, Grécia", interests: ["Cultura", "Gastronomia"], feedback: "", ambassador: false },
  { id: "4", name: "João Pedro Costa", email: "joao.costa@email.com", whatsapp: "+55 41 99123-4567", phone: "(41) 3222-1100", city: "Curitiba", state: "PR", origin: "Feira de Turismo", trip: "Portugal Essencial", classification: "Cliente", status: "Ativo", total: 12780, balance: 0, purchase: 81, churn: 19, cpf: "***.***.***-91", birthday: "09/06/1985", instagram: "@joaopedrocosta", tags: ["Vinho", "Cultura"], observations: "Gosta de viagens com tempo livre para descobrir restaurantes locais.", nps: 9, tripDate: "02 set, 2025", reservation: "RES-2350", embarkation: "Curitiba", seat: "12D · 12E", tripType: "Cultura", package: "Portugal Essencial", insurance: true, minor: false, ticketPrice: 12780, passengers: 2, discount: 0, paid: 12780, installments: 3, commission: 894.6, paymentMethod: "Cartão de crédito", seller: "Marina Duarte", reason: "Férias", rating: 5, profession: "Sommelier", favoriteDrink: "Vinho tinto", music: "Jazz", food: "Portuguesa", dreams: "Toscana, Japão", interests: ["Vinho", "Cultura", "Gastronomia"], feedback: "Atendimento muito atencioso desde o primeiro contato.", ambassador: true },
  { id: "5", name: "Beatriz Souza", email: "bia.souza@email.com", whatsapp: "+55 85 99881-0022", phone: "", city: "Fortaleza", state: "CE", origin: "WhatsApp", trip: "", classification: "Lead", status: "Inativo", total: 3200, balance: 800, purchase: 34, churn: 74, cpf: "***.***.***-63", birthday: "18/12/1990", instagram: "@bia.souza", tags: ["Praia"], observations: "Retomar contato no próximo mês. Ainda comparando datas com o trabalho.", nps: 6, tripDate: "", reservation: "RES-2188", embarkation: "Fortaleza", seat: "", tripType: "Lazer", package: "Pré-reserva", insurance: false, minor: false, ticketPrice: 3200, passengers: 1, discount: 0, paid: 2400, installments: 3, commission: 224, paymentMethod: "Boleto", seller: "Pedro Lima", reason: "Descanso", rating: 3, profession: "Jornalista", favoriteDrink: "Água de coco", music: "Pop", food: "Frutos do mar", dreams: "Fernando de Noronha", interests: ["Praia", "Natureza"], feedback: "", ambassador: false },
];
const money = (n: number) => n.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const blankClient = (): Client => ({ ...seed[2], id: "", name: "", email: "", whatsapp: "", phone: "", city: "", state: "", origin: "WhatsApp", trip: "", classification: "Lead", status: "Lead", total: 0, balance: 0, purchase: 45, churn: 55, cpf: "", birthday: "", instagram: "", tags: [], observations: "", nps: 8, tripDate: "", reservation: "", embarkation: "", seat: "", tripType: "", package: "", insurance: false, minor: false, ticketPrice: 0, passengers: 1, discount: 0, paid: 0, installments: 1, commission: 0, paymentMethod: "A definir", seller: "Ana Ribeiro", reason: "", rating: 0, profession: "", favoriteDrink: "", music: "", food: "", dreams: "", interests: [], feedback: "", ambassador: false, createdAt: new Date().toISOString().slice(0, 10) });
const initials = (name: string) => name.split(" ").map((x) => x[0]).slice(0, 2).join("").toUpperCase() || "VC";
const cls: Record<string, string> = { VIP: "bg-[#f5ead1] text-[#91651f]", Cliente: "bg-[#e7edf0] text-[#53636b]", Prospecto: "bg-[#e9e7dc] text-[#766942]", Lead: "bg-[#f8e4dc] text-[#a34c37]" };
const formAreas = ["Pessoal", "Viagem", "Financeiro", "Experiência", "Preferências", "Agência"];
const profileAreas = ["Dados", "Viagens", "Financeiro", "Fidelidade", "Indicações", "Histórico", "Documentos", "Sonhos", "IA"];
type SortKey = "name" | "total" | "purchase" | "churn";

function Field({ label, value, onChange, placeholder = "", type = "text", hint = "" }: { label: string; value: string | number; onChange: (value: string) => void; placeholder?: string; type?: string; hint?: string }) {
  return <label className="block min-w-0"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">{label}</span><input data-testid={`input-${label.toLocaleLowerCase("pt-BR").replace(/[^a-z0-9]+/g, "-")}`} type={type} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} className="h-10 w-full rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[13px] text-[#243a36] outline-none transition focus:border-[#43847c] focus:ring-2 focus:ring-[#43847c]/15 placeholder:text-[#a0aaa2]" />{hint && <span className="mt-1 block text-[10px] text-[#89958d]">{hint}</span>}</label>;
}
function SectionTitle({ eyebrow, title, note }: { eyebrow: string; title: string; note?: string }) {
  return <div className="mb-5"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-[#43847c]">{eyebrow}</div><div className="mt-1 flex flex-wrap items-baseline justify-between gap-2"><h2 className="font-['Fraunces'] text-[25px] leading-tight text-[#243a36]">{title}</h2>{note && <p className="text-xs text-[#7d8982]">{note}</p>}</div></div>;
}
function Pill({ children, tone = "sage" }: { children: ReactNode; tone?: string }) {
  const tones: Record<string, string> = { sage: "bg-[#e4eee7] text-[#3b7167]", sand: "bg-[#f2eadb] text-[#806941]", coral: "bg-[#f7e5dc] text-[#a4543d]", stone: "bg-[#edf0eb] text-[#66746c]" };
  return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[10px] font-semibold ${tones[tone] ?? tones.sage}`}>{children}</span>;
}

export function ClientWorkspace() {
  const [clients, setClients] = useState<Client[]>(() => seed.map((client, index) => ({ ...client, createdAt: ["2025-06-04", "2025-05-28", "2025-06-12", "2025-05-10", "2025-04-23"][index] })));
  const [view, setView] = useState<"list" | "form" | "profile">("list");
  const [activeClient, setActiveClient] = useState<Client | null>(null);
  const [form, setForm] = useState<Client>(blankClient());
  const [formArea, setFormArea] = useState(0);
  const [profileArea, setProfileArea] = useState(0);
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("Todos");
  const [classFilter, setClassFilter] = useState("Todas");
  const [cityFilter, setCityFilter] = useState("");
  const [originFilter, setOriginFilter] = useState("");
  const [tripFilter, setTripFilter] = useState("Todas as viagens");
  const [sellerFilter, setSellerFilter] = useState("Todos os consultores");
  const [aiFilter, setAiFilter] = useState("Todos os scores");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [sortKey, setSortKey] = useState<SortKey>("name");
  const [sortDirection, setSortDirection] = useState<"asc" | "desc">("asc");
  const [notice, setNotice] = useState("");
  const [deleteTarget, setDeleteTarget] = useState<Client | null>(null);
  const [showFilters, setShowFilters] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  const visible = useMemo(() => {
    const q = query.toLocaleLowerCase("pt-BR").trim();
    const filtered = clients.filter((c) =>
      (!q || [c.name, c.email, c.whatsapp, c.phone, c.city, c.state, c.origin, c.trip, c.id].join(" ").toLocaleLowerCase("pt-BR").includes(q)) &&
      (statusFilter === "Todos" || c.status === statusFilter) &&
      (classFilter === "Todas" || c.classification === classFilter) &&
      (!cityFilter || `${c.city} ${c.state}`.toLocaleLowerCase("pt-BR").includes(cityFilter.toLocaleLowerCase("pt-BR"))) &&
      (!originFilter || c.origin.toLocaleLowerCase("pt-BR").includes(originFilter.toLocaleLowerCase("pt-BR"))) &&
      (tripFilter === "Todas as viagens" || (tripFilter === "Com viagem" ? !!c.trip : tripFilter === "Sem viagem" ? !c.trip : c.trip === tripFilter)) &&
      (sellerFilter === "Todos os consultores" || c.seller === sellerFilter) &&
      (aiFilter === "Todos os scores" || (aiFilter === "Compra alta" ? c.purchase >= 70 : c.churn >= 50)) &&
      (!dateFrom || (c.createdAt ?? "") >= dateFrom) && (!dateTo || (c.createdAt ?? "") <= dateTo)
    );
    return [...filtered].sort((a, b) => {
      const av = a[sortKey], bv = b[sortKey];
      const compare = typeof av === "string" ? av.localeCompare(String(bv), "pt-BR") : Number(av) - Number(bv);
      return sortDirection === "asc" ? compare : -compare;
    });
  }, [clients, query, statusFilter, classFilter, cityFilter, originFilter, tripFilter, sellerFilter, aiFilter, dateFrom, dateTo, sortKey, sortDirection]);
  const totalRevenue = clients.reduce((sum, c) => sum + c.total, 0);
  const activeCount = clients.filter((c) => c.status === "Ativo").length;
  const leadsCount = clients.filter((c) => c.status === "Lead").length;
  const duplicate = form.whatsapp.trim() && clients.some((c) => c.id !== form.id && c.whatsapp.replace(/\D/g, "") === form.whatsapp.replace(/\D/g, ""));
  const missing = ["name", "whatsapp", "cpf"].filter((key) => !String(form[key as keyof Client] ?? "").trim());

  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2800); };
  const startCreate = () => { setForm(blankClient()); setActiveClient(null); setFormArea(0); setView("form"); };
  const startEdit = (client: Client) => { setForm({ ...client }); setActiveClient(client); setFormArea(0); setView("form"); };
  const setField = (key: keyof Client, value: string | number | boolean | string[]) => {
    setForm((old) => {
      const next = { ...old, [key]: value };
      if (key === "ticketPrice" || key === "discount" || key === "paid" || key === "passengers") {
        next.total = Math.max(0, Number(next.ticketPrice) * Number(next.passengers) - Number(next.discount));
        next.balance = Math.max(0, next.total - Number(next.paid));
      }
      return next;
    });
  };
  const saveClient = () => {
    if (!form.name.trim()) { flash("Informe o nome para salvar o cadastro."); setFormArea(0); return; }
    const saved: Client = { ...form, id: form.id || String(Date.now()), classification: form.classification || "Lead", status: form.status || "Lead" };
    setClients((old) => old.some((c) => c.id === saved.id) ? old.map((c) => c.id === saved.id ? saved : c) : [saved, ...old]);
    setActiveClient(saved); setView("profile"); setProfileArea(0); flash(activeClient ? "Cadastro atualizado." : "Cliente adicionado à carteira.");
  };
  const sortBy = (key: SortKey) => {
    if (sortKey === key) setSortDirection((d) => d === "asc" ? "desc" : "asc");
    else { setSortKey(key); setSortDirection(key === "name" ? "asc" : "desc"); }
  };
  const copyClientCode = (client: Client) => {
    const code = `CLI-${client.id.padStart(4, "0").slice(-4)}`;
    if (navigator.clipboard?.writeText) {
      navigator.clipboard.writeText(code).then(() => flash(`Código ${code} copiado.`)).catch(() => flash(`Código do cliente: ${code}`));
    } else flash(`Código do cliente: ${code}`);
  };
  const exportCsv = () => {
    const rows = [["Nome", "Código", "E-mail", "WhatsApp", "Cidade", "UF", "Origem", "Última viagem", "Classificação", "Status", "Gasto total", "Saldo", "Score compra", "Risco churn"], ...visible.map((c) => [c.name, `CLI-${c.id.padStart(4, "0")}`, c.email, c.whatsapp, c.city, c.state, c.origin, c.trip, c.classification, c.status, String(c.total), String(c.balance), String(c.purchase), String(c.churn)])];
    const csv = rows.map((r) => r.map((v) => `"${String(v).replaceAll('"', '""')}"`).join(";")).join("\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob(["\ufeff", csv], { type: "text/csv;charset=utf-8" })); link.download = "carteira-visitecrm.csv"; link.click(); URL.revokeObjectURL(link.href); flash(`${visible.length} clientes exportados.`);
  };
  const importCsv = (file?: File) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const lines = String(reader.result ?? "").split(/\r?\n/).filter(Boolean).slice(1);
      const imported = lines.map((line, i) => {
        const parts = line.includes(";") ? line.split(";") : line.split(",");
        const cleaned = parts.map((x) => x.trim().replace(/^"|"$/g, "").replaceAll('""', '"'));
        const c = blankClient();
        c.id = `${Date.now()}-${i}`; c.name = cleaned[0] || ""; c.email = cleaned[1] || ""; c.whatsapp = cleaned[2] || "";
        c.city = cleaned[3] || ""; c.state = cleaned[4] || ""; c.origin = cleaned[5] || "Importação"; c.status = "Lead";
        return c;
      }).filter((c) => c.name);
      if (imported.length) { setClients((old) => [...imported, ...old]); flash(`${imported.length} contatos importados.`); }
      else flash("Não encontramos contatos válidos. Use Nome; e-mail; WhatsApp; cidade; UF; origem.");
    };
    reader.readAsText(file);
  };
  const goBack = () => { setView("list"); setActiveClient(null); };
  const openProfile = (client: Client) => { setActiveClient(client); setProfileArea(0); setView("profile"); };

  const Topbar = () => <header className="flex h-[62px] items-center justify-between border-b border-[#e3e7de] bg-[#fbfaf5] px-4 md:px-7">
    <div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-[12px] bg-[#234c46] text-[#f5ead2]"><Compass size={19}/></div><div><div className="font-['Fraunces'] text-[17px] leading-none text-[#27423d]">visite<span className="text-[#c96e4e]">.</span></div><div className="mt-1 text-[9px] font-bold uppercase tracking-[.16em] text-[#7a8780]">Relacionamento que leva longe</div></div></div>
    <div className="hidden items-center gap-2 text-[11px] text-[#7c8981] md:flex"><span className="h-2 w-2 rounded-full bg-[#73a18b]"/><span>Carteira sincronizada</span><span className="mx-2 h-4 w-px bg-[#dbe1d7]"/>Unidade Savassi</div>
    <button data-testid="button-notifications" onClick={() => flash("Você está em dia com os acompanhamentos.")} className="relative flex h-9 w-9 items-center justify-center rounded-full border border-[#e3e7de] text-[#60706a] hover:bg-[#f0f2e9]" aria-label="Notificações"><Bell size={16}/><span className="absolute right-[7px] top-[7px] h-1.5 w-1.5 rounded-full bg-[#cf7050]"/></button>
  </header>;

  const Sidebar = () => <aside className="hidden w-[210px] shrink-0 border-r border-[#e2e7de] bg-[#f3f4ec] p-4 lg:block">
    <div className="mb-5 px-3 text-[9px] font-bold uppercase tracking-[.18em] text-[#919c92]">Sua operação</div>
    <button data-testid="nav-clients" aria-current="page" className="mb-1 flex w-full items-center gap-3 rounded-xl bg-[#e1ebe3] px-3 py-2.5 text-left text-[12px] font-semibold text-[#345d53]"><Users size={16}/> Clientes <span className="ml-auto rounded-full bg-[#d1e0d4] px-2 py-0.5 text-[10px]">{clients.length}</span></button>
    {[[Plane, "Viagens"], [CalendarDays, "Agenda"], [Wallet, "Financeiro"]].map(([Icon, label]: any) => <button data-testid={`nav-${String(label).toLowerCase()}`} key={label} onClick={() => flash(`${label}: seção demonstrativa da carteira.`)} className="mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[12px] text-[#707f76] hover:bg-[#e9ede5]"><Icon size={16}/>{label}</button>)}
    <div className="mb-3 mt-8 px-3 text-[9px] font-bold uppercase tracking-[.18em] text-[#919c92]">Acompanhar</div>
    <button data-testid="nav-leads" onClick={() => { setStatusFilter("Lead"); setView("list"); }} className="mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[12px] text-[#707f76] hover:bg-[#e9ede5]"><Clock3 size={16}/> Leads para cuidar <span className="ml-auto text-[10px]">{leadsCount}</span></button>
    <button data-testid="nav-vip" onClick={() => { setClassFilter("VIP"); setView("list"); }} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[12px] text-[#707f76] hover:bg-[#e9ede5]"><Star size={16}/> Clientes especiais</button>
    <div className="mt-10 rounded-2xl bg-[#244a44] p-4 text-[#edf2e9]"><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold"><Sparkles size={14} className="text-[#e2b77c]"/> Um bom momento</div><p className="text-[11px] leading-relaxed text-[#d1dfd4]">{leadsCount} conversas podem virar a próxima grande viagem.</p><button data-testid="button-see-leads" onClick={() => { setStatusFilter("Lead"); setView("list"); }} className="mt-3 text-[10px] font-bold text-[#f0c892]">Ver leads <span aria-hidden>→</span></button></div>
    <div className="mt-7 flex items-center gap-2 border-t border-[#dfe4db] pt-4"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#d9e5dc] text-[10px] font-bold text-[#426b5d]">AR</div><div><div className="text-[11px] font-semibold text-[#354943]">Ana Ribeiro</div><div className="text-[10px] text-[#8a958d]">Consultora sênior</div></div><ChevronDown className="ml-auto text-[#7f8a83]" size={14}/></div>
  </aside>;

  const NavShell = ({ children }: { children: ReactNode }) => <div className="min-h-[100dvh] bg-[#f8f7f0] text-[#253a35]">{Topbar()}<div className="flex min-h-[calc(100dvh-62px)]">{Sidebar()}<main className="min-w-0 flex-1">{children}</main></div>{notice && <div data-testid="status-notice" role="status" className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-xl bg-[#234c46] px-4 py-3 text-[12px] font-medium text-[#f5f2e8] shadow-[0_12px_35px_rgba(31,54,48,.24)]"><Check size={15} className="text-[#bcd4bc]"/>{notice}</div>}</div>;

  const ListView = () => NavShell({ children: <><div className="mx-auto max-w-[1500px] px-4 py-5 md:px-7 md:py-7">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#73847a]"><LayoutGrid size={13}/> Relacionamento <ChevronRight size={12}/> Carteira</div><h1 className="font-['Fraunces'] text-[32px] leading-tight text-[#243a36] md:text-[38px]">Pessoas que viajam com você.</h1><p className="mt-1 text-[13px] text-[#7b8980]">Da primeira conversa ao próximo embarque — tudo em um só lugar.</p></div>
      <div className="flex flex-wrap gap-2"><input data-testid="input-import-csv" aria-label="Selecionar CSV para importar" ref={fileRef} type="file" accept=".csv,.txt" className="hidden" onChange={(e) => importCsv(e.target.files?.[0])}/><button data-testid="button-import-csv" onClick={() => fileRef.current?.click()} className="flex h-10 items-center gap-2 rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[11px] font-semibold text-[#53675f] hover:bg-[#f1f3eb]"><Upload size={15}/> Importar</button><button data-testid="button-export-csv" onClick={exportCsv} className="flex h-10 items-center gap-2 rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[11px] font-semibold text-[#53675f] hover:bg-[#f1f3eb]"><Download size={15}/> Exportar</button><button data-testid="button-new-client" onClick={startCreate} className="flex h-10 items-center gap-2 rounded-xl bg-[#c86f51] px-4 text-[11px] font-bold text-white shadow-sm hover:bg-[#b95f43]"><Plus size={15}/> Novo cliente</button></div>
    </div>
    <section className="mb-5 grid grid-cols-2 gap-3 xl:grid-cols-4">
      {[{ label: "Pessoas na carteira", value: clients.length.toString().padStart(2, "0"), detail: "todos os relacionamentos", icon: Users, accent: "text-[#47796d]", bg: "bg-[#e5eee5]" }, { label: "Em acompanhamento", value: activeCount.toString().padStart(2, "0"), detail: "clientes ativos", icon: BadgeCheck, accent: "text-[#4d806f]", bg: "bg-[#e5eee5]" }, { label: "Novas conversas", value: leadsCount.toString().padStart(2, "0"), detail: "leads na carteira", icon: Send, accent: "text-[#b56b4b]", bg: "bg-[#f5e9dc]" }, { label: "Receita da carteira", value: money(totalRevenue), detail: "valor total contratado", icon: Wallet, accent: "text-[#8e7546]", bg: "bg-[#f1ebdc]" }].map((stat) => <div key={stat.label} className="rounded-2xl border border-[#e3e7de] bg-[#fffefa] p-4 shadow-[0_4px_18px_rgba(54,73,61,.025)]"><div className="flex items-center justify-between"><div className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#7e8b81]">{stat.label}</div><span className={`flex h-8 w-8 items-center justify-center rounded-xl ${stat.bg} ${stat.accent}`}><stat.icon size={16}/></span></div><div className="mt-2 truncate font-['Fraunces'] text-[24px] text-[#2d4841]">{stat.value}</div><div className="mt-1 text-[10px] text-[#929b91]">{stat.detail}</div></div>)}
    </section>
    <section className="overflow-hidden rounded-2xl border border-[#e0e5dc] bg-[#fffefa] shadow-[0_5px_22px_rgba(48,65,54,.035)]">
      <div className="border-b border-[#e7eae2] p-4 md:px-5"><div className="flex flex-wrap items-center gap-2">
        <div className="relative min-w-[220px] flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8c9990]"/><input data-testid="input-client-search" aria-label="Buscar clientes" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar nome, e-mail, WhatsApp, destino..." className="h-10 w-full rounded-xl border border-[#dce2d9] bg-[#fbfaf5] pl-9 pr-3 text-[12px] outline-none focus:border-[#59857a] focus:ring-2 focus:ring-[#59857a]/10"/></div>
        <select data-testid="select-client-status" aria-label="Filtrar por status" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className="h-10 rounded-xl border border-[#dce2d9] bg-[#fbfaf5] px-3 text-[11px] text-[#52635b] outline-none"><option>Todos</option><option>Ativo</option><option>Lead</option><option>Inativo</option></select>
        <select data-testid="select-client-classification" aria-label="Filtrar por classificação" value={classFilter} onChange={(e) => setClassFilter(e.target.value)} className="h-10 rounded-xl border border-[#dce2d9] bg-[#fbfaf5] px-3 text-[11px] text-[#52635b] outline-none"><option>Todas</option><option>VIP</option><option>Cliente</option><option>Prospecto</option><option>Lead</option></select>
        <button data-testid="button-toggle-filters" aria-expanded={showFilters} onClick={() => setShowFilters((s) => !s)} className={`flex h-10 items-center gap-2 rounded-xl border px-3 text-[11px] font-semibold ${showFilters ? "border-[#91b0a0] bg-[#edf3ea] text-[#3b6a5d]" : "border-[#dce2d9] bg-[#fbfaf5] text-[#66746c]"}`}><Filter size={14}/> Mais filtros <ChevronDown size={13}/></button>
      </div>
      {showFilters && <div data-testid="panel-client-filters" className="mt-3 flex flex-wrap gap-2 border-t border-[#edf0e9] pt-3">
        <input data-testid="input-filter-city" aria-label="Filtrar por cidade ou estado" value={cityFilter} onChange={(e) => setCityFilter(e.target.value)} placeholder="Cidade / estado" className="h-9 w-36 rounded-lg border border-[#dce2d9] bg-[#fbfaf5] px-3 text-[11px] outline-none focus:border-[#59857a]"/>
        <input data-testid="input-filter-origin" aria-label="Filtrar por origem" value={originFilter} onChange={(e) => setOriginFilter(e.target.value)} placeholder="Origem do contato" className="h-9 w-40 rounded-lg border border-[#dce2d9] bg-[#fbfaf5] px-3 text-[11px] outline-none focus:border-[#59857a]"/>
        <select data-testid="select-client-trip" aria-label="Filtrar por viagem" value={tripFilter} onChange={(e) => setTripFilter(e.target.value)} className="h-9 rounded-lg border border-[#dce2d9] bg-[#fbfaf5] px-3 text-[11px] text-[#52635b]"><option>Todas as viagens</option><option>Com viagem</option><option>Sem viagem</option>{Array.from(new Set(clients.map((client) => client.trip).filter(Boolean))).map((trip) => <option key={trip}>{trip}</option>)}</select>
        <select data-testid="select-client-seller" aria-label="Filtrar por consultor" value={sellerFilter} onChange={(e) => setSellerFilter(e.target.value)} className="h-9 rounded-lg border border-[#dce2d9] bg-[#fbfaf5] px-3 text-[11px] text-[#52635b]"><option>Todos os consultores</option>{Array.from(new Set(clients.map((client) => client.seller))).map((seller) => <option key={seller}>{seller}</option>)}</select>
        <select data-testid="select-client-ai" aria-label="Filtrar pelos scores de IA" value={aiFilter} onChange={(e) => setAiFilter(e.target.value)} className="h-9 rounded-lg border border-[#dce2d9] bg-[#fbfaf5] px-3 text-[11px] text-[#52635b]"><option>Todos os scores</option><option>Compra alta</option><option>Churn alto</option></select>
        <span className="flex items-center gap-1 rounded-lg bg-[#f2f3ec] px-3 text-[10px] text-[#78867c]"><CalendarDays size={13}/> Cadastro <input data-testid="input-date-from" aria-label="Data inicial do cadastro" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} type="date" className="ml-1 w-[115px] bg-transparent text-[10px] outline-none"/> <span>até</span> <input data-testid="input-date-to" aria-label="Data final do cadastro" value={dateTo} onChange={(e) => setDateTo(e.target.value)} type="date" className="w-[115px] bg-transparent text-[10px] outline-none"/></span>
        <button data-testid="button-clear-filters" onClick={() => { setCityFilter(""); setOriginFilter(""); setTripFilter("Todas as viagens"); setSellerFilter("Todos os consultores"); setAiFilter("Todos os scores"); setStatusFilter("Todos"); setClassFilter("Todas"); setQuery(""); setDateFrom(""); setDateTo(""); }} className="ml-auto text-[10px] font-semibold text-[#a46147]">Limpar filtros</button>
      </div>}
      </div>
      <div className="flex items-center justify-between px-5 py-3"><div data-testid="text-client-result-count" className="text-[11px] text-[#7f8b82]"><strong className="text-[#44584f]">{visible.length}</strong> pessoas encontradas</div><div className="flex items-center gap-2 text-[10px] text-[#89958c]"><span>Ordenar por</span><select data-testid="select-client-sort" aria-label="Ordenar clientes por" value={sortKey} onChange={(e) => { setSortKey(e.target.value as SortKey); setSortDirection("desc"); }} className="rounded-lg border border-[#e1e6de] bg-[#fbfaf5] px-2 py-1.5 text-[10px] text-[#53655c]"><option value="name">Nome</option><option value="total">Gasto total</option><option value="purchase">Score de compra</option><option value="churn">Risco de churn</option></select><button data-testid="button-sort-direction" onClick={() => setSortDirection((d) => d === "asc" ? "desc" : "asc")} className="flex h-7 w-7 items-center justify-center rounded-lg border border-[#e1e6de] text-[#718077]" aria-label="Inverter ordenação">{sortDirection === "asc" ? <ArrowUpDown size={13}/> : <ArrowDown size={13}/>}</button></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[930px] border-collapse text-left"><thead><tr className="border-y border-[#e8ebe4] bg-[#f7f7f0] text-[9px] font-bold uppercase tracking-[.11em] text-[#879288]">
        <th scope="col" aria-sort={sortKey === "name" ? (sortDirection === "asc" ? "ascending" : "descending") : "none"} className="px-4 py-3"><button data-testid="sort-name" onClick={() => sortBy("name")} className="inline-flex items-center gap-1.5 text-left">Cliente <ArrowUpDown size={10}/></button></th>
        <th scope="col" className="px-3 py-3">Contato</th><th scope="col" className="px-3 py-3">Jornada</th><th scope="col" className="px-3 py-3">Relacionamento</th>
        <th scope="col" aria-sort={sortKey === "total" ? (sortDirection === "asc" ? "ascending" : "descending") : "none"} className="px-3 py-3"><button data-testid="sort-total" onClick={() => sortBy("total")} className="inline-flex items-center gap-1.5 text-left">Financeiro <ArrowUpDown size={10}/></button></th>
        <th scope="col" className="px-3 py-3"><div className="mb-1">Scores IA</div><div className="flex gap-2 text-[8px] font-semibold tracking-normal"><button data-testid="sort-purchase-score" aria-label="Ordenar por score de compra" onClick={() => sortBy("purchase")} className="inline-flex items-center gap-1">Compra <ArrowUpDown size={9}/></button><button data-testid="sort-churn-score" aria-label="Ordenar por risco de churn" onClick={() => sortBy("churn")} className="inline-flex items-center gap-1">Churn <ArrowUpDown size={9}/></button></div></th>
        <th scope="col" className="px-3 py-3">Ações</th></tr></thead>
        <tbody>{visible.map((c) => <tr data-testid={`row-client-${c.id}`} key={c.id} className="group border-b border-[#edf0e9] transition-colors hover:bg-[#fbfaf4]">
          <td className="px-4 py-3"><div className="flex items-start gap-2.5"><span className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#e5eee6] font-['Fraunces'] text-[13px] text-[#416b5d]">{initials(c.name)}</span><div className="min-w-0"><button data-testid={`button-open-client-${c.id}`} onClick={() => openProfile(c)} className="block max-w-full truncate text-left text-[12px] font-semibold text-[#344a41] hover:text-[#3e7766]">{c.name}</button><div className="mt-0.5 max-w-[180px] truncate text-[10px] text-[#929b91]">{c.email || "Sem e-mail"}</div><button data-testid={`button-copy-code-${c.id}`} aria-label={`Copiar código de ${c.name}`} onClick={() => copyClientCode(c)} className="mt-1 inline-flex items-center gap-1 rounded-md border border-[#e4e8df] bg-[#f6f6ef] px-1.5 py-0.5 font-mono text-[9px] text-[#77847a] hover:border-[#b5c9b9] hover:text-[#486d5c]">CLI-{c.id.padStart(4, "0").slice(-4)} <Copy size={10}/></button></div></div></td>
          <td className="px-3 py-3"><div className="whitespace-nowrap text-[11px] font-medium text-[#4c6258]">{c.whatsapp || "—"}</div><div className="mt-1 whitespace-nowrap text-[10px] text-[#9aa39a]">{c.phone || "Sem telefone fixo"}</div></td>
          <td className="px-3 py-3"><div className="whitespace-nowrap text-[11px] text-[#586b61]"><MapPin size={12} className="mr-1 inline text-[#98a59b]"/>{c.city ? `${c.city}, ${c.state}` : "Localidade não informada"}</div><div className="mt-1"><Pill tone="stone">{c.origin}</Pill></div><div className="mt-1 max-w-[190px] truncate text-[10px] text-[#6b7a70]" title={c.trip || undefined}><Plane size={11} className="mr-1 inline text-[#91a394]"/>{c.trip || "Sem viagem recente"}</div></td>
          <td className="px-3 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${cls[c.classification]}`}>{c.classification}</span><div className="mt-2 inline-flex items-center gap-1.5 whitespace-nowrap text-[10px] text-[#65776c]"><span className={`h-1.5 w-1.5 rounded-full ${c.status === "Ativo" ? "bg-[#76a68b]" : c.status === "Lead" ? "bg-[#d38a64]" : "bg-[#a7ada5]"}`}/>{c.status}</div></td>
          <td className="px-3 py-3"><div className="whitespace-nowrap text-[11px] font-semibold text-[#40594e]">{money(c.total)}</div><div className={`mt-1 whitespace-nowrap text-[10px] ${c.balance ? "font-semibold text-[#b36648]" : "text-[#89958b]"}`}>Em aberto {money(c.balance)}</div></td>
          <td className="px-3 py-3"><div className="flex items-center gap-1.5"><span className="text-[9px] text-[#929c92]">Compra</span><span className="rounded-lg bg-[#e8f0e8] px-1.5 py-0.5 text-[10px] font-bold text-[#477a65]">{c.purchase}%</span></div><div className="mt-1.5 flex items-center gap-1.5"><span className="text-[9px] text-[#929c92]">Churn</span><span className={`rounded-lg px-1.5 py-0.5 text-[10px] font-bold ${c.churn >= 50 ? "bg-[#f7e5dc] text-[#a7573e]" : "bg-[#f1ecdc] text-[#8f7748]"}`}>{c.churn}%</span></div></td>
          <td className="px-3"><div className="flex items-center gap-1 opacity-80 group-hover:opacity-100"><button data-testid={`button-view-${c.id}`} aria-label={`Ver perfil de ${c.name}`} onClick={() => openProfile(c)} title="Ver perfil" className="flex h-8 w-8 items-center justify-center rounded-lg text-[#718178] hover:bg-[#e8eee6]"><UserRound size={14}/></button><button data-testid={`button-edit-${c.id}`} aria-label={`Editar ${c.name}`} onClick={() => startEdit(c)} title="Editar" className="flex h-8 w-8 items-center justify-center rounded-lg text-[#718178] hover:bg-[#e8eee6]"><MoreHorizontal size={15}/></button><button data-testid={`button-whatsapp-${c.id}`} aria-label={`WhatsApp ${c.name}`} onClick={() => flash(`WhatsApp de ${c.name}: ${c.whatsapp || "contato não informado"}`)} title="WhatsApp" className="flex h-8 w-8 items-center justify-center rounded-lg text-[#54816b] hover:bg-[#e8eee6]"><Send size={14}/></button><button data-testid={`button-delete-${c.id}`} aria-label={`Excluir ${c.name}`} onClick={() => setDeleteTarget(c)} title="Excluir cliente (admin)" className="flex h-8 w-8 items-center justify-center rounded-lg text-[#b36a54] hover:bg-[#f8e8e0]"><Trash2 size={13}/></button></div></td>
        </tr>)}</tbody></table></div>
      {visible.length === 0 && <div className="flex flex-col items-center py-14 text-center"><div className="mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-[#edf1e9] text-[#71877a]"><Search size={20}/></div><div className="font-['Fraunces'] text-[20px] text-[#344b42]">Nenhuma pessoa por aqui</div><p className="mt-1 text-[12px] text-[#87938a]">Tente ajustar os filtros ou cadastre um novo contato.</p><button onClick={startCreate} className="mt-4 rounded-xl bg-[#c86f51] px-4 py-2 text-[11px] font-bold text-white">Adicionar cliente</button></div>}
      <div className="flex items-center justify-between px-5 py-3 text-[10px] text-[#929a91]"><span>Exibindo {visible.length ? 1 : 0}–{visible.length} de {visible.length}</span><div className="flex items-center gap-1"><button disabled className="flex h-7 w-7 items-center justify-center rounded-lg border border-[#e7eae3] disabled:opacity-40"><ChevronLeft size={13}/></button><span className="px-2 text-[#597468]">1</span><button disabled className="flex h-7 w-7 items-center justify-center rounded-lg border border-[#e7eae3] disabled:opacity-40"><ChevronRight size={13}/></button></div></div>
    </section>
    <div className="mt-4 flex items-center gap-2 text-[10px] text-[#9aa39a]"><ShieldCheck size={13} className="text-[#7f9b83]"/> Dados protegidos · Acesso administrativo registrado</div>
  </div>
  {deleteTarget && <div className="fixed inset-0 z-40 flex items-center justify-center bg-[#1c302b]/35 p-4" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && setDeleteTarget(null)}><div role="dialog" aria-modal="true" className="w-full max-w-[390px] rounded-2xl border border-[#e3e7de] bg-[#fffefa] p-5 shadow-2xl"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f7e5dc] text-[#ae5e46]"><CircleAlert size={18}/></span><div><h3 className="font-['Fraunces'] text-[20px] text-[#344b42]">Excluir cadastro?</h3><p className="mt-1 text-[12px] leading-relaxed text-[#7e8980]">A ação administrativa removerá <strong>{deleteTarget.name}</strong> desta carteira local.</p></div></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setDeleteTarget(null)} className="rounded-xl border border-[#dce2d9] px-4 py-2 text-[11px] font-semibold text-[#607067]">Manter cadastro</button><button onClick={() => { setClients((old) => old.filter((c) => c.id !== deleteTarget.id)); flash(`${deleteTarget.name} removido da carteira.`); setDeleteTarget(null); }} className="rounded-xl bg-[#ad5b43] px-4 py-2 text-[11px] font-bold text-white">Excluir</button></div></div></div>}
  </> });

  const FormView = () => {
    const update = (key: keyof Client) => (value: string) => setField(key, value);
    const checkbox = (key: "insurance" | "minor" | "ambassador", label: string) => <label className="flex cursor-pointer items-center gap-2.5 rounded-xl border border-[#e0e6dc] bg-[#fbfaf5] px-3 py-3 text-[11px] text-[#53665c]"><input data-testid={`input-${key}`} type="checkbox" checked={form[key]} onChange={(e) => setField(key, e.target.checked)} className="h-4 w-4 accent-[#3f776b]"/>{label}</label>;
    const checkTag = (key: "interests" | "tags", options: string[]) => <div className="flex flex-wrap gap-2">{options.map((tag) => { const chosen = form[key].includes(tag); return <button data-testid={`toggle-${key}-${tag.toLowerCase().replaceAll(" ", "-")}`} type="button" key={tag} aria-pressed={chosen} onClick={() => setField(key, chosen ? form[key].filter((x) => x !== tag) : [...form[key], tag])} className={`rounded-full border px-3 py-1.5 text-[10px] font-semibold transition ${chosen ? "border-[#92b19d] bg-[#e4eee6] text-[#416f60]" : "border-[#dfe5dc] bg-[#fffefa] text-[#7c8980] hover:border-[#acc3b2]"}`}>{chosen && <Check size={10} className="mr-1 inline"/>}{tag}</button>; })}</div>;
    return NavShell({ children: <div className="mx-auto max-w-[1100px] px-4 py-5 md:px-7 md:py-7">
      <button data-testid="button-back-to-client-list" onClick={goBack} className="mb-5 flex items-center gap-2 text-[11px] font-semibold text-[#708178] hover:text-[#3c665a]"><ArrowLeft size={14}/> Voltar para carteira</button>
      <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.17em] text-[#739080]">{activeClient ? "Cadastro em edição" : "Novo relacionamento"}</div><h1 className="mt-1 font-['Fraunces'] text-[32px] text-[#263e38]">{activeClient ? form.name || "Editar cliente" : "Comece pela pessoa."}</h1><p className="mt-1 text-[12px] text-[#819087]">Um bom roteiro começa com boas perguntas.</p></div><div className="flex items-center gap-2"><span className="rounded-lg border border-[#dfe5dc] bg-[#fffefa] px-3 py-2 font-mono text-[10px] text-[#78857c]">{activeClient ? `CLI-${form.id.padStart(4, "0").slice(-4)}` : "NOVO CADASTRO"}</span></div></div>
      {(duplicate || missing.length > 0) && <div className="mb-4 grid gap-2 md:grid-cols-2">{duplicate && <div className="flex items-start gap-2 rounded-xl border border-[#e9c5ab] bg-[#fbf0e6] px-3.5 py-3 text-[11px] text-[#915b3c]"><CircleAlert size={15} className="mt-0.5 shrink-0"/><span><strong>Contato possivelmente duplicado.</strong> Este WhatsApp já aparece em outro cadastro. Confirme antes de salvar.</span></div>}{missing.length > 0 && <div className="flex items-start gap-2 rounded-xl border border-[#e7d7a8] bg-[#faf5e4] px-3.5 py-3 text-[11px] text-[#8b7141]"><CircleAlert size={15} className="mt-0.5 shrink-0"/><span><strong>Dados essenciais pendentes:</strong> {missing.map((m) => ({ name: "nome", whatsapp: "WhatsApp", cpf: "CPF" }[m])).join(", ")}. É possível salvar e completar depois.</span></div>}</div>}
      <div className="grid gap-5 lg:grid-cols-[235px_minmax(0,1fr)]">
        <aside className="self-start rounded-2xl border border-[#e1e6dc] bg-[#fffefa] p-3"><div className="px-2 pb-3 pt-1 text-[9px] font-bold uppercase tracking-[.15em] text-[#9aa297]">Cadastro completo</div>{formAreas.map((area, i) => <button data-testid={`tab-form-${i + 1}`} aria-current={formArea === i ? "step" : undefined} key={area} onClick={() => setFormArea(i)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition ${formArea === i ? "bg-[#e8efe7] text-[#3d6d5f]" : "text-[#6e7d74] hover:bg-[#f4f5ef]"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-lg text-[10px] font-bold ${formArea === i ? "bg-[#d4e3d6]" : "bg-[#f0f1ea]"}`}>{String(i + 1).padStart(2, "0")}</span><span className="text-[11px] font-semibold">{area}</span><ChevronRight size={13} className="ml-auto opacity-50"/></button>)}<div className="mt-4 rounded-xl bg-[#f5f3e9] p-3 text-[10px] leading-relaxed text-[#81877b]"><span className="font-semibold text-[#5c6d61]">Dica de atendimento</span><br/>As preferências tornam o próximo contato mais pessoal.</div></aside>
        <section className="min-h-[535px] rounded-2xl border border-[#e1e6dc] bg-[#fffefa] p-4 md:p-6">
          {formArea === 0 && <><SectionTitle eyebrow="01 · Identidade" title="Dados pessoais e contato" note="* Campos importantes para localizar a pessoa"/><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Nome completo *" value={form.name} onChange={update("name")} placeholder="Como gosta de ser chamada"/></div><Field label="WhatsApp *" value={form.whatsapp} onChange={update("whatsapp")} placeholder="+55 (31) 99999-0000"/><Field label="Telefone alternativo" value={form.phone} onChange={update("phone")} placeholder="(31) 3333-0000"/><Field label="E-mail" value={form.email} onChange={update("email")} placeholder="nome@email.com"/><Field label="Instagram" value={form.instagram} onChange={update("instagram")} placeholder="@perfil"/><Field label="CPF" value={form.cpf} onChange={update("cpf")} placeholder="000.000.000-00"/><Field label="Data de aniversário" value={form.birthday} onChange={update("birthday")} placeholder="dd/mm/aaaa"/><Field label="Cidade" value={form.city} onChange={update("city")} placeholder="Belo Horizonte"/><Field label="Estado" value={form.state} onChange={update("state")} placeholder="MG"/><label className="block"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">Origem do contato</span><select value={form.origin} onChange={(e) => setField("origin", e.target.value)} className="h-10 w-full rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[12px] text-[#40584e]"><option>Indicação</option><option>Instagram</option><option>Site</option><option>WhatsApp</option><option>Feira de Turismo</option><option>Importação</option><option>Outro</option></select></label><label className="block"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">Classificação</span><select value={form.classification} onChange={(e) => setField("classification", e.target.value)} className="h-10 w-full rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[12px] text-[#40584e]">{["Lead", "Prospecto", "Cliente", "VIP"].map((x) => <option key={x}>{x}</option>)}</select></label><label className="block"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">Status do relacionamento</span><select value={form.status} onChange={(e) => setField("status", e.target.value)} className="h-10 w-full rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[12px] text-[#40584e]">{["Lead", "Ativo", "Inativo"].map((x) => <option key={x}>{x}</option>)}</select></label></div></>}
          {formArea === 1 && <><SectionTitle eyebrow="02 · Roteiro" title="Viagem e reserva" note="Da intenção até o embarque"/><div className="grid gap-4 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">Viagem ou destino de interesse</span><select value={form.trip} onChange={(e) => setField("trip", e.target.value)} className="h-10 w-full rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[12px] text-[#40584e]"><option value="">Ainda não definido</option>{["Lençóis Maranhenses", "Patagônia Argentina", "Portugal Essencial", "Fernando de Noronha", "Japão em flor"].map((x) => <option key={x}>{x}</option>)}</select></label><Field label="Código da reserva" value={form.reservation} onChange={update("reservation")} placeholder="RES-0000"/><Field label="Data da viagem" value={form.tripDate} onChange={update("tripDate")} placeholder="18 jul, 2025"/><Field label="Local de embarque" value={form.embarkation} onChange={update("embarkation")} placeholder="Cidade / aeroporto"/><Field label="Assento(s)" value={form.seat} onChange={update("seat")} placeholder="14A · 14B"/><Field label="Tipo de viagem" value={form.tripType} onChange={update("tripType")} placeholder="Lazer, aventura, lua de mel..."/><Field label="Pacote / acomodação" value={form.package} onChange={update("package")} placeholder="Nome do pacote ou quarto"/><div className="pt-1">{checkbox("insurance", "Seguro viagem contratado")}</div><div className="pt-1">{checkbox("minor", "Viaja com criança menor de 7 anos")}</div></div></>}
          {formArea === 2 && <><SectionTitle eyebrow="03 · Valores" title="Financeiro e condições" note="Os totais são atualizados automaticamente"/><div className="grid gap-4 sm:grid-cols-2"><Field label="Preço por passageiro (R$)" type="number" value={form.ticketPrice} onChange={update("ticketPrice")} placeholder="0,00"/><Field label="Quantidade de passageiros" type="number" value={form.passengers} onChange={update("passengers")} placeholder="1"/><Field label="Desconto (R$)" type="number" value={form.discount} onChange={update("discount")} placeholder="0,00"/><Field label="Valor já pago (R$)" type="number" value={form.paid} onChange={update("paid")} placeholder="0,00"/><Field label="Parcelas" type="number" value={form.installments} onChange={update("installments")} placeholder="1"/><Field label="Comissão (R$)" type="number" value={form.commission} onChange={update("commission")} placeholder="0,00"/><label className="block"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">Forma de pagamento</span><select value={form.paymentMethod} onChange={(e) => setField("paymentMethod", e.target.value)} className="h-10 w-full rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[12px]"><option>A definir</option><option>Pix</option><option>Cartão de crédito</option><option>Pix + cartão</option><option>Boleto</option><option>Transferência</option></select></label><label className="block"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">Consultor responsável</span><select value={form.seller} onChange={(e) => setField("seller", e.target.value)} className="h-10 w-full rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[12px]"><option>Ana Ribeiro</option><option>Pedro Lima</option><option>Marina Duarte</option><option>Sem responsável</option></select></label></div><div className="mt-5 grid grid-cols-3 gap-2 rounded-2xl bg-[#f2f4ec] p-3"><div><div className="text-[9px] font-semibold uppercase tracking-wide text-[#7d8c7f]">Valor total</div><div className="mt-1 text-[14px] font-bold text-[#35594d]">{money(form.total)}</div></div><div><div className="text-[9px] font-semibold uppercase tracking-wide text-[#7d8c7f]">Desconto</div><div className="mt-1 text-[14px] font-bold text-[#66776a]">{money(form.discount)}</div></div><div><div className="text-[9px] font-semibold uppercase tracking-wide text-[#a76a4e]">Falta pagar</div><div className="mt-1 text-[14px] font-bold text-[#a75d43]">{money(form.balance)}</div></div></div></>}
          {formArea === 3 && <><SectionTitle eyebrow="04 · Contexto" title="Motivo, avaliação e observações" note="Informação que ajuda a cuidar melhor"/><div className="grid gap-4"><label className="block max-w-sm"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">Motivo da viagem</span><select value={form.reason} onChange={(e) => setField("reason", e.target.value)} className="h-10 w-full rounded-xl border border-[#dbe1d7] bg-[#fffefa] px-3 text-[12px]"><option value="">Não especificado</option>{["Férias em família", "Lua de mel", "Aventura", "Descanso", "Cultura", "Negócios", "Comemoração"].map((x) => <option key={x}>{x}</option>)}</select></label><div><div className="mb-2 text-[11px] font-semibold tracking-wide text-[#61716e]">Avaliação interna do relacionamento · {form.rating}/5</div><div className="flex gap-2">{[1, 2, 3, 4, 5].map((n) => <button key={n} onClick={() => setField("rating", n)} className={`flex h-10 w-10 items-center justify-center rounded-xl border ${n <= form.rating ? "border-[#d9ba78] bg-[#f5ebd5] text-[#ae8541]" : "border-[#dfe5dc] bg-[#fffefa] text-[#9aa399]"}`}><Star size={15} fill={n <= form.rating ? "currentColor" : "none"}/></button>)}</div></div><label className="block"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">Observações sobre a pessoa</span><textarea value={form.observations} onChange={(e) => setField("observations", e.target.value)} rows={6} placeholder="Preferências, contexto familiar, próximos passos..." className="w-full resize-y rounded-xl border border-[#dbe1d7] bg-[#fffefa] p-3 text-[12px] leading-relaxed text-[#354c42] outline-none focus:border-[#43847c]"/></label></div></>}
          {formArea === 4 && <><SectionTitle eyebrow="05 · Preferências" title="Um jeito de viajar único" note="Pequenos detalhes fazem diferença"/><div className="grid gap-4 sm:grid-cols-2"><Field label="Área de atuação profissional" value={form.profession} onChange={update("profession")} placeholder="Profissão"/><Field label="Bebida favorita" value={form.favoriteDrink} onChange={update("favoriteDrink")} placeholder="Vinho, café..."/><Field label="Preferências musicais" value={form.music} onChange={update("music")} placeholder="MPB, jazz..."/><Field label="Preferências gastronômicas" value={form.food} onChange={update("food")} placeholder="Culinária local..."/><div className="sm:col-span-2"><Field label="Destinos sonhados · separados por vírgula" value={form.dreams} onChange={update("dreams")} placeholder="Fernando de Noronha, Japão, Toscana"/></div><div className="sm:col-span-2"><div className="mb-2 text-[11px] font-semibold tracking-wide text-[#61716e]">Interesses</div>{checkTag("interests", ["Praia", "Aventura", "Cultura", "Gastronomia", "Natureza", "Vinho", "Família", "Bem-estar"])}</div><div className="sm:col-span-2"><div className="mb-2 text-[11px] font-semibold tracking-wide text-[#61716e]">Tags da carteira</div>{checkTag("tags", ["VIP", "Família", "Praia", "Aventura", "Lua de mel", "Cultura", "Vinho"])}</div></div></>}
          {formArea === 5 && <><SectionTitle eyebrow="06 · Agência" title="Nossa relação com a agência" note="Escuta ativa, confiança e boas histórias"/><div className="rounded-2xl bg-[#f3f4eb] p-4"><div className="flex items-center justify-between"><div><div className="text-[11px] font-semibold text-[#40584d]">NPS · recomendaria a Visite?</div><div className="mt-1 text-[10px] text-[#8a9589]">0 detrator <span className="mx-2">·</span> 6 neutro <span className="mx-2">·</span> 10 promotor</div></div><span className="font-['Fraunces'] text-[30px] text-[#3b7567]">{form.nps}<span className="text-[14px] text-[#8da092]">/10</span></span></div><input aria-label="Nota NPS" type="range" min="0" max="10" value={form.nps} onChange={(e) => setField("nps", Number(e.target.value))} className="mt-4 w-full accent-[#4c8475]"/></div><label className="mt-4 block"><span className="mb-1.5 block text-[11px] font-semibold tracking-wide text-[#61716e]">Comentário ou feedback sobre a agência</span><textarea value={form.feedback} onChange={(e) => setField("feedback", e.target.value)} rows={5} placeholder="O que marcou a experiência? O que podemos fazer melhor?" className="w-full resize-y rounded-xl border border-[#dbe1d7] bg-[#fffefa] p-3 text-[12px] outline-none focus:border-[#43847c]"/></label><div className="mt-4 max-w-md">{checkbox("ambassador", "Participa do Programa de Embaixadores")}</div></>}
          <div className="mt-7 flex flex-wrap items-center justify-between gap-3 border-t border-[#edf0e9] pt-4"><button data-testid="button-form-back" onClick={() => formArea > 0 ? setFormArea(formArea - 1) : goBack()} className="flex items-center gap-2 rounded-xl px-3 py-2 text-[11px] font-semibold text-[#718077] hover:bg-[#f4f5ef]"><ArrowLeft size={14}/> {formArea > 0 ? "Etapa anterior" : "Cancelar"}</button><div className="flex gap-2"><button data-testid="button-form-next" onClick={() => setFormArea((formArea + 1) % formAreas.length)} className="flex items-center gap-2 rounded-xl border border-[#dce3da] px-4 py-2.5 text-[11px] font-semibold text-[#53685d] hover:bg-[#f4f5ef]">Próxima etapa <ArrowRight size={13}/></button><button data-testid="button-save-client" onClick={saveClient} className="rounded-xl bg-[#c86f51] px-5 py-2.5 text-[11px] font-bold text-white shadow-sm hover:bg-[#b95f43]">{activeClient ? "Salvar alterações" : "Criar cliente"}</button></div></div>
        </section>
      </div>
    </div> });
  };

  const ProfileView = () => {
    if (!activeClient) return null;
    const c = clients.find((x) => x.id === activeClient.id) ?? activeClient;
    const detail = (label: string, value: string, icon?: ReactNode) => <div className="flex min-w-0 gap-2.5"><span className="mt-0.5 text-[#85a092]">{icon}</span><div className="min-w-0"><div className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#94a095]">{label}</div><div className="mt-1 break-words text-[12px] font-medium text-[#43584f]">{value || "—"}</div></div></div>;
    return NavShell({ children: <div className="mx-auto max-w-[1100px] px-4 py-5 md:px-7 md:py-7">
      <button onClick={goBack} className="mb-5 flex items-center gap-2 text-[11px] font-semibold text-[#708178] hover:text-[#3c665a]"><ArrowLeft size={14}/> Voltar para carteira</button>
      <section className="overflow-hidden rounded-2xl border border-[#e0e5dc] bg-[#fffefa]">
        <div className="relative overflow-hidden bg-[#244a44] px-5 py-5 text-[#f5f3e8] md:px-7"><div className="pointer-events-none absolute -right-8 -top-24 h-60 w-60 rounded-full border border-[#8ca99a]/20"/><div className="pointer-events-none absolute right-24 -top-28 h-64 w-64 rounded-full border border-[#8ca99a]/15"/><div className="relative flex flex-wrap items-center gap-4"><div className="flex h-[58px] w-[58px] items-center justify-center rounded-[19px] border border-white/10 bg-[#e5eee2] font-['Fraunces'] text-[20px] text-[#3a6959]">{initials(c.name)}</div><div className="min-w-[180px] flex-1"><div className="flex flex-wrap items-center gap-2"><h1 data-testid="text-profile-name" className="font-['Fraunces'] text-[29px] leading-none">{c.name}</h1><span data-testid="status-profile-classification" className="rounded-full bg-[#e7dcc3] px-2.5 py-1 text-[9px] font-bold text-[#735d37]">{c.classification}</span></div><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-[10px] text-[#c7d7ca]"><span>{c.email || "Sem e-mail"}</span><span>·</span><span>{c.city ? `${c.city}, ${c.state}` : "Localidade não informada"}</span><span>·</span><span className="font-mono">CLI-{c.id.padStart(4, "0").slice(-4)}</span></div></div><div className="flex gap-2"><button data-testid="button-profile-whatsapp" aria-label={`WhatsApp ${c.name}`} onClick={() => flash(`WhatsApp de ${c.name}: ${c.whatsapp || "contato não informado"}`)} className="flex h-9 items-center gap-2 rounded-xl border border-[#8ea89b]/40 px-3 text-[10px] font-semibold text-[#ecf0e5] hover:bg-white/10"><Send size={13}/> WhatsApp</button><button data-testid="button-profile-edit" onClick={() => startEdit(c)} className="flex h-9 items-center gap-2 rounded-xl bg-[#d2e2d3] px-3 text-[10px] font-bold text-[#315d50] hover:bg-[#e1ebde]"><MoreHorizontal size={14}/> Editar</button></div></div><div className="relative mt-4 flex flex-wrap gap-2">{c.tags.map((tag) => <span key={tag} className="rounded-full border border-white/15 bg-white/5 px-2.5 py-1 text-[9px] text-[#d2ded1]">#{tag.toLocaleLowerCase("pt-BR")}</span>)}</div></div>
        <div className="grid grid-cols-2 border-b border-[#e7ebe3] bg-[#f8f8f1] md:grid-cols-4">{[{ label: "Valor contratado", value: money(c.total), detail: "Receita da viagem", icon: Wallet }, { label: "Valor pago", value: money(Math.max(0, c.total - c.balance)), detail: c.paymentMethod, icon: CreditCard }, { label: "Saldo em aberto", value: money(c.balance), detail: c.balance ? "Acompanhar parcelas" : "Tudo em dia", icon: Clock3 }, { label: "NPS da agência", value: `${c.nps}/10`, detail: c.nps >= 9 ? "Promotor da marca" : "Voz do cliente", icon: Star }].map((m, i) => <div key={m.label} className={`px-4 py-4 md:px-5 ${i % 2 ? "border-l border-[#e7ebe3] md:border-l" : ""} ${i > 1 ? "border-t border-[#e7ebe3] md:border-t-0" : ""} ${i > 0 ? "md:border-l" : ""}`}><div className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.1em] text-[#879389]"><m.icon size={13} className="text-[#799583]"/>{m.label}</div><div className="mt-1 font-['Fraunces'] text-[21px] text-[#34564a]">{m.value}</div><div className="mt-0.5 text-[9px] text-[#9aa399]">{m.detail}</div></div>)}</div>
      </section>
      <div className="mt-5 grid gap-5 lg:grid-cols-[215px_minmax(0,1fr)]">
        <aside className="h-fit rounded-2xl border border-[#e1e6dc] bg-[#fffefa] p-3"><div className="px-2 pb-3 pt-1 text-[9px] font-bold uppercase tracking-[.15em] text-[#9aa297]">Visão 360°</div>{profileAreas.map((area, i) => <button data-testid={`tab-profile-${i + 1}`} aria-current={profileArea === i ? "page" : undefined} key={area} onClick={() => setProfileArea(i)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left ${profileArea === i ? "bg-[#e8efe7] text-[#3d6d5f]" : "text-[#6e7d74] hover:bg-[#f4f5ef]"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-lg ${profileArea === i ? "bg-[#d4e3d6]" : "bg-[#f0f1ea]"}`}>{[<UserRound size={13}/>, <Plane size={13}/>, <CreditCard size={13}/>, <Heart size={13}/>, <Users size={13}/>, <History size={13}/>, <FileText size={13}/>, <MapPin size={13}/>, <Sparkles size={13}/>][i]}</span><span className="text-[11px] font-semibold">{area}</span><ChevronRight size={13} className="ml-auto opacity-40"/></button>)}</aside>
        <section className="min-h-[430px] rounded-2xl border border-[#e1e6dc] bg-[#fffefa] p-4 md:p-6">
          {profileArea === 0 && <><SectionTitle eyebrow="01 · Pessoa" title="Dados do relacionamento" note={`Atualizado hoje · Origem: ${c.origin}`}/><div className="grid gap-5 sm:grid-cols-2">{detail("WhatsApp", c.whatsapp, <Send size={14}/>)}{detail("E-mail", c.email, <FileText size={14}/>)}{detail("Telefone", c.phone, <Users size={14}/>)}{detail("Localidade", c.city ? `${c.city} / ${c.state}` : "", <MapPin size={14}/>)}{detail("Aniversário", c.birthday, <CalendarDays size={14}/>)}{detail("CPF", c.cpf, <ShieldCheck size={14}/>)}{detail("Instagram", c.instagram, <Heart size={14}/>)}{detail("Pipeline", c.status === "Lead" ? "Novo contato" : "Cliente em relacionamento", <Compass size={14}/>)}{detail("Consultor", c.seller, <UserRound size={14}/>)}{detail("Classificação", c.classification, <Star size={14}/>)}</div><div className="mt-6 border-t border-[#edf0e9] pt-4"><div className="mb-2 text-[9px] font-bold uppercase tracking-[.13em] text-[#929c91]">O que importa para esta pessoa</div><p className="rounded-xl bg-[#f5f5ed] p-3 text-[11px] leading-relaxed text-[#67776b]">{c.observations || "Nenhuma observação registrada."}</p></div></>}
          {profileArea === 1 && <><SectionTitle eyebrow="02 · Jornadas" title="Viagens e reservas" note="Histórias vividas e próximas partidas"/>{c.trip ? <div className="rounded-2xl border border-[#e3e8df] bg-[#fbfaf5] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Pill>Reserva confirmada</Pill><h3 className="mt-3 font-['Fraunces'] text-[23px] text-[#34564a]">{c.trip}</h3><div className="mt-2 flex flex-wrap gap-3 text-[10px] text-[#829087]"><span className="flex items-center gap-1"><CalendarDays size={12}/>{c.tripDate || "Data a definir"}</span><span className="flex items-center gap-1"><MapPin size={12}/>{c.embarkation || c.city}</span><span>{c.reservation || "Sem código"}</span></div></div><Plane className="text-[#78a08d]" size={22}/></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#e6e9e0] pt-4 md:grid-cols-4">{detail("Passageiros", String(c.passengers), <Users size={13}/>)}{detail("Assento(s)", c.seat, <Plane size={13}/>)}{detail("Pacote", c.package, <BriefcaseBusiness size={13}/>)}{detail("Seguro viagem", c.insurance ? "Contratado" : "Não contratado", <ShieldCheck size={13}/>)}</div></div> : <div className="rounded-2xl border border-dashed border-[#dce4d9] bg-[#fafaf4] px-6 py-10 text-center"><Plane className="mx-auto text-[#8eaa97]" size={23}/><h3 className="mt-3 font-['Fraunces'] text-[20px] text-[#405d50]">A próxima história começa aqui</h3><p className="mt-1 text-[11px] text-[#89968c]">Ainda não há uma viagem vinculada a este cadastro.</p><button onClick={() => startEdit(c)} className="mt-4 rounded-xl bg-[#c86f51] px-4 py-2 text-[10px] font-bold text-white">Planejar viagem</button></div>}</>}
          {profileArea === 2 && <><SectionTitle eyebrow="03 · Pagamentos" title="Financeiro e parcelas" note={c.balance ? "Há um saldo que merece acompanhamento" : "Nenhum saldo pendente"}/><div className="mb-4 grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-[#f0f4ec] p-3"><div className="text-[9px] uppercase tracking-wide text-[#879487]">Total da viagem</div><div className="mt-1 text-[17px] font-bold text-[#426b57]">{money(c.total)}</div></div><div className="rounded-xl bg-[#f0f4ec] p-3"><div className="text-[9px] uppercase tracking-wide text-[#879487]">Já recebido</div><div className="mt-1 text-[17px] font-bold text-[#426b57]">{money(Math.max(0, c.total - c.balance))}</div></div><div className="rounded-xl bg-[#f8eee5] p-3"><div className="text-[9px] uppercase tracking-wide text-[#a88266]">Em aberto</div><div className="mt-1 text-[17px] font-bold text-[#a95f43]">{money(c.balance)}</div></div></div>{[{ label: "Reserva / entrada", value: Math.min(c.total, c.paid), status: c.paid > 0 ? "Pago" : "Pendente" }, { label: `Parcelas · ${c.installments}x`, value: c.balance, status: c.balance > 0 ? "Em aberto" : "Pago" }, { label: "Comissão da agência", value: c.commission, status: "Registrada" }].map((p, i) => <div key={p.label} className="mb-2 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#e7eae2] p-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#eef2e9] text-[#6e8a78]"><CreditCard size={14}/></span><div><div className="text-[11px] font-semibold text-[#4d6257]">{p.label}</div><div className="mt-0.5 text-[9px] text-[#929d93]">{i < 2 ? c.paymentMethod : `Consultor · ${c.seller}`}</div></div></div><div className="flex items-center gap-3"><span className="text-[12px] font-semibold text-[#455c50]">{money(p.value)}</span><Pill tone={p.status === "Em aberto" ? "coral" : "sage"}>{p.status}</Pill></div></div>)}</>}
          {profileArea === 3 && <><SectionTitle eyebrow="04 · Reconhecimento" title="Fidelidade e recorrência" note="Valoriza quem escolhe viajar junto"/><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-[#edf2e8] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wide text-[#738571]"><Star size={14}/> Pontos disponíveis</div><div className="mt-3 font-['Fraunces'] text-[32px] text-[#3d6954]">2.450 <span className="text-[13px]">pts</span></div><div className="text-[10px] text-[#809080]">Equivalente a {money(245)} em experiências</div></div><div className="rounded-2xl bg-[#f4efe2] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wide text-[#92805f]"><BadgeCheck size={14}/> Categoria</div><div className="mt-3 font-['Fraunces'] text-[25px] text-[#796640]">{c.classification === "VIP" ? "Ouro" : "Viajante"}</div><div className="text-[10px] text-[#92866e]">5.820 pontos acumulados na jornada</div></div></div><div className="mt-4 rounded-xl border border-[#e6e9e0] p-4"><div className="flex justify-between text-[10px] text-[#829087]"><span>Próxima categoria</span><span>72% do caminho</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#edf0e8]"><div className="h-full w-[72%] rounded-full bg-[#7ea084]"/></div><p className="mt-2 text-[10px] text-[#87938a]">Mais uma viagem para desbloquear benefícios exclusivos.</p></div></>}
          {profileArea === 4 && <><SectionTitle eyebrow="05 · Comunidade" title="Indicações e embaixadores" note="Boas viagens rendem boas conversas"/><div className="rounded-2xl border border-[#e5e9df] bg-[#fbfaf5] p-5"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wide text-[#879389]"><Users size={14}/> Código pessoal de indicação</div><div className="mt-2 flex flex-wrap items-center gap-3"><span className="font-mono text-[25px] font-bold tracking-[.05em] text-[#3d7162]">{c.name.split(" ")[0].toUpperCase()}25</span><button onClick={() => { void navigator.clipboard?.writeText(`${c.name.split(" ")[0].toUpperCase()}25`); flash("Código de indicação copiado."); }} className="rounded-lg border border-[#dfe5dc] px-3 py-1.5 text-[10px] font-semibold text-[#61756a]">Copiar código</button><Pill>{c.ambassador ? "Embaixador ativo" : "Programa disponível"}</Pill></div><div className="mt-5 grid grid-cols-2 gap-4 border-t border-[#e6e9e0] pt-4"><div><div className="text-[9px] uppercase tracking-wide text-[#929b90]">Indicações realizadas</div><div className="mt-1 font-['Fraunces'] text-[25px] text-[#395f51]">{c.ambassador ? "03" : "00"}</div></div><div><div className="text-[9px] uppercase tracking-wide text-[#929b90]">Convertidas em viagem</div><div className="mt-1 font-['Fraunces'] text-[25px] text-[#395f51]">{c.ambassador ? "02" : "00"}</div></div></div></div></>}
          {profileArea === 5 && <><SectionTitle eyebrow="06 · Memória" title="Histórico de relacionamento" note="Um fio contínuo de cuidado"/>{[{ title: c.trip ? `Reserva criada · ${c.trip}` : "Primeiro contato recebido", date: "Hoje · 10:42", description: c.trip ? `Reserva ${c.reservation || "em andamento"} vinculada ao cadastro.` : `Origem: ${c.origin}. Consultor responsável: ${c.seller}.` }, { title: "Conversa de acompanhamento", date: "12 jun · 15:20", description: "Roteiro e preferências conversados por WhatsApp." }, { title: "Cadastro atualizado", date: "03 jun · 09:14", description: "Preferências e detalhes pessoais revisados." }].map((event, i) => <div key={event.title} className="relative flex gap-3 pb-5 last:pb-0"><div className="relative flex w-8 shrink-0 justify-center"><span className={`z-10 flex h-7 w-7 items-center justify-center rounded-full ${i === 0 ? "bg-[#deebe0] text-[#55806b]" : "bg-[#f0f1ea] text-[#88948a]"}`}><History size={13}/></span>{i < 2 && <span className="absolute top-7 h-full w-px bg-[#e4e8df]"/>}</div><div className="pt-0.5"><div className="text-[11px] font-semibold text-[#4b6256]">{event.title}</div><div className="mt-1 text-[9px] text-[#96a095]">{event.date}</div><p className="mt-1 text-[10px] text-[#7c8980]">{event.description}</p></div></div>)}</>}
          {profileArea === 6 && <><SectionTitle eyebrow="07 · Arquivo" title="Documentos" note="Arquivos úteis para a próxima viagem"/><div className="rounded-2xl border border-dashed border-[#dce3d9] bg-[#fafaf4] px-5 py-10 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#eaf0e8] text-[#6e8f7a]"><FileText size={21}/></span><h3 className="mt-3 font-['Fraunces'] text-[20px] text-[#405b4f]">Nenhum documento anexado</h3><p className="mt-1 text-[10px] text-[#89968c]">Passaporte, vouchers e comprovantes podem ficar reunidos aqui.</p><button onClick={() => flash("Anexos ficam disponíveis ao conectar o armazenamento da agência.")} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-[#dce3d9] bg-[#fffefa] px-4 py-2 text-[10px] font-semibold text-[#5b7467]"><Upload size={13}/> Enviar documento</button></div></>}
          {profileArea === 7 && <><SectionTitle eyebrow="08 · Próximos capítulos" title="Destinos dos sonhos" note="Ideias para manter a conversa viva"/><div className="grid gap-2 sm:grid-cols-2">{(c.dreams || "Sem destinos cadastrados").split(",").map((place) => <div key={place} className="flex items-center gap-3 rounded-xl border border-[#e5e9e0] bg-[#fbfaf5] p-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#e8efe8] text-[#718f7b]"><MapPin size={14}/></span><span className="text-[12px] font-semibold text-[#50665a]">{place.trim()}</span><Heart size={13} className="ml-auto text-[#c88368]"/></div>)}</div><div className="mt-5 rounded-xl bg-[#f4f3e9] p-4"><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-wide text-[#7f8c7d]"><Tag size={13}/> Interesses de viagem</div><div className="flex flex-wrap gap-2">{c.interests.map((x) => <Pill key={x} tone="stone">{x}</Pill>)}</div></div></>}
          {profileArea === 8 && <><SectionTitle eyebrow="09 · Sinais" title="Leitura de relacionamento" note="Indicadores para orientar, não substituir, a conversa"/><div className="rounded-2xl bg-[#edf2e8] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wide text-[#537866]"><Sparkles size={15}/> Próxima boa conversa</div><p className="mt-3 font-['Fraunces'] text-[22px] leading-snug text-[#34594b]">{c.purchase >= 70 ? "Momento favorável para inspirar a próxima viagem." : "Um cuidado próximo pode reabrir caminhos."}</p><p className="mt-2 max-w-lg text-[11px] leading-relaxed text-[#718278]">{c.purchase >= 70 ? `A relação tem bons sinais de recorrência. Que tal retomar ${c.dreams.split(",")[0] || "os destinos que ela sonha"}?` : "O interesse ainda pode amadurecer. Vale perguntar sobre datas e oferecer opções flexíveis."}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-[#e4e9df] p-4"><div className="text-[10px] text-[#87948a]">Score de compra</div><div className="mt-1 flex items-end justify-between"><span className="font-['Fraunces'] text-[28px] text-[#4c8068]">{c.purchase}%</span><span className="pb-1 text-[9px] text-[#829184]">próximos 90 dias</span></div><div className="mt-2 h-1.5 rounded-full bg-[#edf0e8]"><div style={{ width: `${c.purchase}%` }} className="h-full rounded-full bg-[#7da58b]"/></div></div><div className="rounded-xl border border-[#e4e9df] p-4"><div className="text-[10px] text-[#87948a]">Risco de churn</div><div className="mt-1 flex items-end justify-between"><span className={`font-['Fraunces'] text-[28px] ${c.churn >= 50 ? "text-[#b7694e]" : "text-[#92794b]"}`}>{c.churn}%</span><span className="pb-1 text-[9px] text-[#829184]">atenção da equipe</span></div><div className="mt-2 h-1.5 rounded-full bg-[#f1eee5]"><div style={{ width: `${c.churn}%` }} className={`h-full rounded-full ${c.churn >= 50 ? "bg-[#d58b68]" : "bg-[#c9b27b]"}`}/></div></div></div><button onClick={() => flash("Indicadores atualizados localmente com os dados da carteira.")} className="mt-4 rounded-xl border border-[#dce4d9] px-4 py-2 text-[10px] font-semibold text-[#577365] hover:bg-[#f4f6ef]">Recalcular leitura</button></>}
        </section>
      </div>
    </div> });
  };

  return view === "form" ? FormView() : view === "profile" ? ProfileView() : ListView();
}