import "./_group.css";
import { useMemo, useState } from "react";
import { Search, Plus, Download, Upload, MoreHorizontal, MapPin, Users, UserCheck, TrendingUp, X, Phone, Mail, Calendar, FileText, Gift, Star, Plane, CreditCard } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Client = { id:string; name:string; email:string; whatsapp:string; phone:string; city:string; state:string; origin:string; trip:string; classification:string; status:string; total:number; balance:number; purchase:number; churn:number; cpf:string; birthday:string; tags:string[]; observations:string; nps:number; };
const seed: Client[] = [
  {id:"1",name:"Mariana Alves",email:"mariana.alves@email.com",whatsapp:"+55 31 99876-3210",phone:"(31) 3344-2211",city:"Belo Horizonte",state:"MG",origin:"Indicação",trip:"Lençóis Maranhenses",classification:"VIP",status:"Ativo",total:18450,balance:0,purchase:92,churn:8,cpf:"***.***.***-42",birthday:"14/08/1988",tags:["vip","família","praia"],observations:"Prefere experiências exclusivas e hotéis boutique.",nps:10},
  {id:"2",name:"Ricardo Mendes",email:"ricardo.mendes@gmail.com",whatsapp:"+55 11 98765-1098",phone:"",city:"São Paulo",state:"SP",origin:"Instagram",trip:"Patagônia Argentina",classification:"Cliente",status:"Ativo",total:9250,balance:1450,purchase:76,churn:24,cpf:"***.***.***-08",birthday:"02/11/1979",tags:["aventura"],observations:"Viajante frequente, gosta de roteiros de aventura.",nps:9},
  {id:"3",name:"Camila Ferreira",email:"camila.ferreira@outlook.com",whatsapp:"+55 21 99654-7788",phone:"",city:"Rio de Janeiro",state:"RJ",origin:"Site",trip:"",classification:"Prospecto",status:"Lead",total:0,balance:0,purchase:58,churn:42,cpf:"***.***.***-16",birthday:"27/03/1993",tags:["lua de mel"],observations:"",nps:8},
  {id:"4",name:"João Pedro Costa",email:"joao.costa@email.com",whatsapp:"+55 41 99123-4567",phone:"(41) 3222-1100",city:"Curitiba",state:"PR",origin:"Feira de Turismo",trip:"Portugal Essencial",classification:"Cliente",status:"Ativo",total:12780,balance:0,purchase:81,churn:19,cpf:"***.***.***-91",birthday:"09/06/1985",tags:["vinho","cultura"],observations:"",nps:9},
  {id:"5",name:"Beatriz Souza",email:"bia.souza@email.com",whatsapp:"+55 85 99881-0022",phone:"",city:"Fortaleza",state:"CE",origin:"WhatsApp",trip:"",classification:"Lead",status:"Inativo",total:3200,balance:800,purchase:34,churn:74,cpf:"***.***.***-63",birthday:"18/12/1990",tags:["praia"],observations:"Retomar contato no próximo mês.",nps:6},
];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const cls={Lead:"bg-blue-50 text-blue-700 border-blue-200",Prospecto:"bg-purple-50 text-purple-700 border-purple-200",Cliente:"bg-slate-50 text-slate-700 border-slate-200",VIP:"bg-amber-50 text-amber-700 border-amber-200"};
const fields=[["Nome Completo","name"],["WhatsApp","whatsapp"],["CPF","cpf"],["E-mail","email"],["Instagram","instagram"],["Data de Aniversário","birthday"],["Cidade","city"],["Estado","state"]];
const formTabs=[["personal","Pessoal"],["trip","Viagem"],["financial","Financeiro"],["observations","Obs."],["followup","Follow-up"],["agency","Agência"]];
const profileTabs=[["data","Dados"],["trips","Viagens"],["financial","Financeiro"],["loyalty","Fidelidade"],["referral","Indicações"],["history","Histórico"],["documents","Docs"],["dreams","Sonhos"],["ia","IA"]];

function ClientForm({open,onClose,client,onSave}:{open:boolean;onClose:()=>void;client:Client|null;onSave:(c:Client)=>void}) {
  const [tab,setTab]=useState("personal"); const [name,setName]=useState(client?.name??""); const [email,setEmail]=useState(client?.email??""); const [whatsapp,setWhatsapp]=useState(client?.whatsapp??"");
  const save=()=>{ if(!name.trim()) return; onSave({...client??seed[0],id:client?.id??String(Date.now()),name,email,whatsapp,status:client?.status??"Lead",classification:client?.classification??"Lead"}); onClose(); };
  return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{client?`Editar: ${client.name}`:"Novo Cliente"}</DialogTitle></DialogHeader>
    <Tabs value={tab} onValueChange={setTab}><TabsList className="flex w-full justify-start overflow-x-auto text-xs">{formTabs.map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList>
      <TabsContent value="personal" className="space-y-4 mt-4"><div className="grid grid-cols-2 gap-4">{fields.map(([label,key],i)=><div key={key} className={i===0?"col-span-2 space-y-2":"space-y-2"}><label className="text-sm font-medium">{label}{i<3&&!client&&" *"}</label><Input type={key==="birthday"?"date":"text"} value={key==="name"?name:key==="email"?email:key==="whatsapp"?whatsapp:(client as any)?.[key]??""} onChange={e=>key==="name"?setName(e.target.value):key==="email"?setEmail(e.target.value):key==="whatsapp"?setWhatsapp(e.target.value):undefined} placeholder={label}/></div>)}</div><div className="rounded-lg border border-amber-200 bg-amber-50/70 p-3 text-xs text-amber-900">Permitir cadastro com dados ausentes</div></TabsContent>
      <TabsContent value="trip" className="space-y-4 mt-4"><label className="text-sm font-medium">Viagem</label><Select><SelectTrigger><SelectValue placeholder="Selecionar viagem..." /></SelectTrigger><SelectContent><SelectItem value="none">Nenhuma</SelectItem><SelectItem value="lencois">Lençóis Maranhenses — 18/07/2025</SelectItem><SelectItem value="portugal">Portugal Essencial — 02/09/2025</SelectItem></SelectContent></Select><div className="grid grid-cols-2 gap-4"><Input placeholder="Local de Embarque"/><Input placeholder="Poltrona"/><Input placeholder="Tipo de Viagem"/><Input placeholder="Pacote / Quarto"/></div><label className="flex gap-2 text-sm"><input type="checkbox"/> Possui Seguro de Viagem</label><label className="flex gap-2 text-sm"><input type="checkbox"/> Criança menor de 7 anos</label></TabsContent>
      <TabsContent value="financial" className="space-y-4 mt-4"><div className="grid grid-cols-2 gap-4">{["Preço da Passagem (R$)","Quantidade de Passageiros","Desconto (R$)","Valor Já Pago (R$)","Parcelas","Comissão (R$)"].map(x=><div className="space-y-2" key={x}><label className="text-sm font-medium">{x}</label><Input type="number" placeholder="0,00"/></div>)}</div><Select><SelectTrigger><SelectValue placeholder="Forma de Pagamento"/></SelectTrigger><SelectContent><SelectItem value="pix">Pix</SelectItem><SelectItem value="card">Cartão de crédito</SelectItem><SelectItem value="boleto">Boleto</SelectItem></SelectContent></Select><div className="grid grid-cols-3 gap-3 border-t pt-3">{["Valor Total","Desconto","Falta Pagar"].map(x=><div className="rounded-lg border bg-muted/30 p-3" key={x}><p className="text-xs text-muted-foreground">{x}</p><b>{money(0)}</b></div>)}</div></TabsContent>
      <TabsContent value="observations" className="space-y-4 mt-4"><label className="text-sm font-medium">Motivo da Viagem</label><Select><SelectTrigger><SelectValue placeholder="Não especificado"/></SelectTrigger><SelectContent><SelectItem value="leisure">Lazer</SelectItem><SelectItem value="business">Negócios</SelectItem></SelectContent></Select><label className="text-sm font-medium">Avaliação Interna (0–5)</label><div className="flex gap-2">{[1,2,3,4,5].map(n=><Button variant="outline" key={n}>{n}</Button>)}</div><Textarea placeholder="Anotações livres sobre o cliente..." rows={6}/></TabsContent>
      <TabsContent value="followup" className="space-y-4 mt-4"><div className="grid grid-cols-2 gap-4">{["Área de Atuação Profissional","Bebida Favorita","Preferências Musicais","Preferências Gastronômicas"].map(x=><Input key={x} placeholder={x}/>)}</div><Input placeholder="Destinos Sonhados (separe por vírgulas)"/><Input placeholder="Tags (vip, família, aventura)"/><div className="flex flex-wrap gap-2">{["Praia","Aventura","Cultura","Gastronomia","Natureza"].map(x=><Badge key={x} variant="outline">{x}</Badge>)}</div></TabsContent>
      <TabsContent value="agency" className="space-y-4 mt-4"><label className="text-sm font-medium">NPS — Nota do cliente à agência (0–10)</label><input className="w-full accent-primary" type="range" min="0" max="10" defaultValue="8"/><div className="flex justify-between text-xs text-muted-foreground"><span>0 — Detrator</span><span>6 — Neutro</span><span>10 — Promotor</span></div><Textarea placeholder="Comentário sobre a Agência" rows={5}/><label className="flex gap-2 text-sm"><input type="checkbox"/> Participante do Programa de Embaixadores</label></TabsContent>
    </Tabs><DialogFooter><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={save}>{client?"Salvar Alterações":"Criar Cliente"}</Button></DialogFooter></DialogContent></Dialog>
}

function Profile({client,onClose}:{client:Client;onClose:()=>void}) {
 const [tab,setTab]=useState("data"); return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto"><DialogHeader><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center text-primary text-lg font-bold">{client.name[0]}</div><div><DialogTitle>{client.name}</DialogTitle><p className="text-sm text-muted-foreground">{client.email}</p><span className="font-mono text-xs text-muted-foreground">Código de Registro: CLI-{client.id.padStart(4,"0")}</span></div><Badge className={`ml-auto ${cls[client.classification as keyof typeof cls]}`}>{client.status}</Badge></div></DialogHeader>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3 py-2">{[["Valor Total",money(client.total)],["Valor Pago",money(client.total-client.balance)],["Saldo Devedor",money(client.balance)],["NPS",`${client.nps}/10`]].map(([l,v])=><Card className="p-3" key={l}><p className="text-xs text-muted-foreground">{l}</p><p className="text-lg font-bold">{v}</p></Card>)}</div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="grid w-full grid-cols-9">{profileTabs.map(([v,l])=><TabsTrigger key={v} value={v} className="text-xs">{l}</TabsTrigger>)}</TabsList>
 <TabsContent value="data" className="space-y-4 mt-4"><div className="grid grid-cols-2 gap-4">{[["WhatsApp",client.whatsapp,Phone],["E-mail",client.email,Mail],["Cidade",`${client.city}/${client.state}`,MapPin],["Aniversário",client.birthday,Calendar],["CPF",client.cpf,null],["Classificação",client.classification,null],["Pipeline","Reserva Criada",null],["Instagram","@"+client.name.split(" ")[0].toLowerCase(),null]].map(([l,v,I]: any)=><div className="flex gap-2" key={l}>{I&&<I className="w-4 h-4 text-muted-foreground"/>}<div><p className="text-xs text-muted-foreground">{l}</p><p className="font-medium">{v}</p></div></div>)}</div><div><p className="text-xs text-muted-foreground mb-1">Tags</p>{client.tags.map(t=><Badge variant="outline" className="mr-1" key={t}>{t}</Badge>)}</div><p className="text-sm bg-muted/50 rounded-lg p-3">{client.observations||"Nenhuma observação registrada."}</p></TabsContent>
 <TabsContent value="trips" className="mt-4"><div className="p-4 rounded-lg border"><div className="flex justify-between"><b>{client.trip||"Nenhuma viagem encontrada."}</b>{client.trip&&<Badge>Confirmada</Badge>}</div><p className="text-xs text-muted-foreground mt-2">18/07/2025 · 2 lugar(es) · Assento 14</p><p className="font-semibold mt-3">{money(client.total)}</p></div></TabsContent>
 <TabsContent value="financial" className="mt-4 space-y-2">{["Entrada da reserva","Parcela 2/3","Taxa de serviço"].map((x,i)=><div className="flex justify-between p-3 rounded-lg border" key={x}><div><b>{x}</b><p className="text-xs text-muted-foreground">Vence 18/06/2025</p></div><div className="text-right"><b>{money([3000,1250,250][i])}</b><Badge className="ml-2">Pago</Badge></div></div>)}</TabsContent>
 <TabsContent value="loyalty" className="mt-4 grid grid-cols-2 gap-3"><Card className="p-4"><p className="text-xs text-muted-foreground">Pontos Disponíveis</p><p className="text-2xl font-bold text-primary">2.450</p><p className="text-xs text-muted-foreground">≈ {money(245)}</p></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Tier</p><Badge className="mt-2 bg-yellow-100 text-yellow-800">Ouro</Badge><p className="text-xl font-bold mt-2">5.820 pts</p></Card></TabsContent>
 <TabsContent value="referral" className="mt-4"><Card className="p-4"><p className="text-sm text-muted-foreground">Código de indicação</p><p className="text-2xl font-mono font-bold text-primary">MARIANA25</p><Badge className="mt-2">Ativo</Badge><p className="mt-4 text-sm">Indicações bem-sucedidas: <b>3</b></p></Card></TabsContent>
 <TabsContent value="history" className="mt-4 space-y-3">{["Pagamento recebido","Reserva criada","WhatsApp — Roteiro enviado"].map((x,i)=><div className="flex gap-3 border-b pb-3" key={x}><div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center"><Calendar className="w-4 h-4 text-blue-600"/></div><div><b className="text-sm">{x}</b><p className="text-xs text-muted-foreground">{i+1} de junho de 2025 às 14:30</p></div></div>)}</TabsContent>
 <TabsContent value="documents" className="mt-4"><div className="border rounded-lg p-8 text-center text-muted-foreground"><FileText className="w-8 h-8 mx-auto mb-2 opacity-40"/>Nenhum documento enviado ainda.<Button variant="outline" className="block mx-auto mt-4"><Upload className="w-4 h-4 mr-2"/>Enviar Documento</Button></div></TabsContent>
 <TabsContent value="dreams" className="mt-4 space-y-2">{["Fernando de Noronha","Morro de São Paulo"].map(x=><div className="p-3 rounded-lg border flex gap-2" key={x}><MapPin className="w-4 h-4 text-muted-foreground"/><b>{x}</b></div>)}</TabsContent>
 <TabsContent value="ia" className="mt-4"><Card className="p-4"><div className="flex items-center gap-2"><Star className="text-yellow-500"/><b>Score de compra: {client.purchase}%</b></div><p className="text-sm text-muted-foreground mt-2">Alta probabilidade de nova compra nos próximos 90 dias.</p><Button variant="outline" className="mt-4">Recalcular score</Button></Card></TabsContent>
 </Tabs></DialogContent></Dialog>
}

export function Current() {
 const [clients,setClients]=useState(seed); const [query,setQuery]=useState(""); const [form,setForm]=useState<{open:boolean;client:Client|null}>({open:false,client:null}); const [profile,setProfile]=useState<Client|null>(null);
 const visible=useMemo(()=>clients.filter(c=>[c.name,c.email,c.whatsapp,c.city].join(" ").toLowerCase().includes(query.toLowerCase())),[clients,query]);
 const stats=[["Total",clients.length,Users,"bg-blue-100 text-blue-600"],["Ativos",clients.filter(c=>c.status==="Ativo").length,UserCheck,"bg-green-100 text-green-600"],["Leads",clients.filter(c=>c.status==="Lead").length,TrendingUp,"bg-purple-100 text-purple-600"],["Receita Total",money(clients.reduce((n,c)=>n+c.total,0)),TrendingUp,"bg-yellow-100 text-yellow-600"]];
 return <div className="client-records-sandbox min-h-screen bg-background text-foreground p-5 space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Clientes</h1><p className="text-sm text-muted-foreground">Gerencie sua carteira de clientes.</p></div><div className="flex gap-2"><Button variant="outline" size="sm"><Upload className="w-4 h-4 mr-1"/>Importar planilha</Button><Button variant="outline" size="sm"><Download className="w-4 h-4 mr-1"/>Exportar CSV</Button><Button size="sm" onClick={()=>setForm({open:true,client:null})}><Plus className="w-4 h-4 mr-1"/>Novo Cliente</Button></div></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(([label,value,I,color]: any)=><Card className="p-4" key={label}><div className="flex items-center gap-3"><div className={`w-9 h-9 rounded-lg flex items-center justify-center ${color}`}><I className="w-5 h-5"/></div><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-xl font-bold">{value}</p></div></div></Card>)}</div>
 <Card><CardHeader className="pb-3 space-y-3"><div className="flex flex-wrap gap-2"><div className="relative flex-1 min-w-[220px]"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar por nome, email, WhatsApp..." value={query} onChange={e=>setQuery(e.target.value)}/></div><Select><SelectTrigger className="w-36"><SelectValue placeholder="Status"/></SelectTrigger><SelectContent><SelectItem value="all">Todos os status</SelectItem><SelectItem value="active">Ativo</SelectItem><SelectItem value="lead">Lead</SelectItem></SelectContent></Select><Select><SelectTrigger className="w-36"><SelectValue placeholder="Classificação"/></SelectTrigger><SelectContent><SelectItem value="all">Todas</SelectItem><SelectItem value="vip">VIP</SelectItem><SelectItem value="client">Cliente</SelectItem></SelectContent></Select></div><div className="flex flex-wrap gap-2"><Input placeholder="Filtrar por cidade..." className="w-36"/><Input placeholder="Filtrar por origem..." className="w-36"/><Select><SelectTrigger className="w-44"><SelectValue placeholder="Viagem de interesse"/></SelectTrigger><SelectContent><SelectItem value="all">Todas as viagens</SelectItem></SelectContent></Select><div className="flex items-center gap-1 text-xs text-muted-foreground">De: <Input type="date" className="w-36"/> Até: <Input type="date" className="w-36"/></div></div></CardHeader>
 <CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left">{["Cliente","Código","Contato","Localidade","Origem","Última Viagem","Classificação","Status","Gasto Total","Saldo","Score IA","Risco Churn","Ações"].map(h=><th className="h-10 px-3 text-xs font-medium text-muted-foreground whitespace-nowrap" key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(c=><tr className="border-b hover:bg-muted/30" key={c.id}><td className="px-3 py-3"><button className="flex items-center gap-3 text-left" onClick={()=>setProfile(c)}><div className="w-9 h-9 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold">{c.name[0]}</div><div><p className="font-medium">{c.name}</p><p className="text-xs text-muted-foreground">{c.email}</p></div></button></td><td className="px-3"><span className="font-mono text-[10px] px-1.5 py-0.5 rounded bg-muted border">CLI-{c.id.padStart(4,"0")}</span></td><td className="px-3 whitespace-nowrap"><p>{c.whatsapp}</p><p className="text-xs text-muted-foreground">{c.phone}</p></td><td className="px-3 whitespace-nowrap"><MapPin className="inline w-3 h-3 mr-1 text-muted-foreground"/>{c.city}/{c.state}</td><td className="px-3"><span className="text-xs bg-blue-50 text-blue-700 border border-blue-200 rounded-full px-2 py-0.5">{c.origin}</span></td><td className="px-3 text-xs text-muted-foreground">{c.trip||"—"}</td><td className="px-3"><Badge variant="outline" className={cls[c.classification as keyof typeof cls]}>{c.classification}</Badge></td><td className="px-3"><Badge variant="outline">{c.status}</Badge></td><td className="px-3 font-medium whitespace-nowrap">{money(c.total)}</td><td className="px-3 whitespace-nowrap">{money(c.balance)}</td><td className="px-3"><span className="text-xs rounded-full px-1.5 py-0.5 bg-green-100 text-green-700">{c.purchase}%</span></td><td className="px-3"><span className="text-xs rounded-full px-1.5 py-0.5 bg-yellow-100 text-yellow-700">{c.churn}%</span></td><td className="px-3"><Button variant="ghost" size="icon" onClick={()=>setForm({open:true,client:c})}><MoreHorizontal className="w-4 h-4"/></Button></td></tr>)}</tbody></table></CardContent></Card>
 <ClientForm open={form.open} client={form.client} onClose={()=>setForm({open:false,client:null})} onSave={c=>setClients(prev=>prev.some(x=>x.id===c.id)?prev.map(x=>x.id===c.id?c:x):[...prev,c])}/>{profile&&<Profile client={profile} onClose={()=>setProfile(null)}/>}</div>;
}