// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/client-records/ClientWorkspace.tsx": () => import("../components/mockups/client-records/ClientWorkspace.tsx"),
  "./components/mockups/client-records/Current.tsx": () => import("../components/mockups/client-records/Current.tsx")
};
